-- Généré par tools/gen_seed.py depuis Catalog.swift : ne pas modifier à la main.
begin;

insert into public.musicians (id, name, band, arcana_title, arcana_number, instruments, subgenre) values
  ('knocked-loose', 'Bryan Garris', 'Knocked Loose', 'The Deadringer', 'IV', array['chant']::text[], 'Hardcore'),
  ('isaac-hale', 'Isaac Hale', 'Knocked Loose', 'Counting Worms', 'X', array['guitare']::text[], 'Hardcore'),
  ('jinjer', 'Tatiana Shmayluk', 'Jinjer', 'Pisces', 'V', array['chant']::text[], 'Metalcore progressif'),
  ('spiritbox', 'Courtney LaPlante', 'Spiritbox', 'Holy Roller', 'VI', array['chant']::text[], 'Metalcore'),
  ('landmvrks', 'Florent Salfati', 'Landmvrks', 'Lost in the Waves', 'VIII', array['chant']::text[], 'Metalcore'),
  ('ramos', 'Will Ramos', 'Lorna Shore', 'To the Hellfire', 'XIV', array['chant']::text[], 'Deathcore'),
  ('heriot', 'Debbie Gough', 'Heriot', 'Devoured by the Mouth of Hell', 'XVIII', array['chant', 'guitare']::text[], 'Metalcore'),
  ('duplantier', 'Mario Duplantier', 'Gojira', 'Flying Whales', 'XVI', array['batterie']::text[], 'Death metal progressif'),
  ('blink182', 'Travis Barker', 'Blink-182', 'All the Small Things', 'VII', array['batterie']::text[], 'Pop punk'),
  ('hoppus', 'Mark Hoppus', 'Blink-182', 'What''s My Age Again?', 'XII', array['basse', 'chant']::text[], 'Pop punk'),
  ('hendrix', 'Jimi Hendrix', 'Jimi Hendrix', 'Purple Haze', 'IX', array['guitare']::text[], 'Rock psychédélique'),
  ('korn', 'Jonathan Davis', 'Korn', 'Freak on a Leash', 'XI', array['chant']::text[], 'Nu metal'),
  ('poppy', 'Poppy', 'Poppy', 'I Disagree', 'XIII', array['chant']::text[], 'Métal expérimental'),
  ('slash', 'Slash', 'Guns N'' Roses', 'Welcome to the Jungle', 'XV', array['guitare']::text[], 'Hard rock'),
  ('zack', 'Zack de la Rocha', 'Rage Against the Machine', 'Bulls on Parade', 'XVII', array['chant']::text[], 'Rap metal'),
  ('frusciante', 'John Frusciante', 'Red Hot Chili Peppers', 'Under the Bridge', 'XIX', array['guitare']::text[], 'Funk rock'),
  ('root', 'Jim Root', 'Slipknot', 'Duality', 'XX', array['guitare']::text[], 'Nu metal'),
  ('jordison', 'Joey Jordison', 'Slipknot', 'Wait and Bleed', 'XXI', array['batterie']::text[], 'Nu metal')
on conflict (id) do nothing;

insert into public.cards (musician_id, rarity, image_path) values
  ('knocked-loose', 'commune', 'cards/knocked-loose-commune.jpg'),
  ('knocked-loose', 'rare', 'cards/knocked-loose-rare.jpg'),
  ('knocked-loose', 'holo', 'cards/knocked-loose-holo.jpg'),
  ('knocked-loose', 'signature', 'cards/knocked-loose-signature.jpg'),
  ('knocked-loose', 'legendaire', 'cards/knocked-loose-legendaire.jpg'),
  ('isaac-hale', 'commune', 'cards/isaac-hale-commune.jpg'),
  ('isaac-hale', 'rare', 'cards/isaac-hale-rare.jpg'),
  ('isaac-hale', 'holo', 'cards/isaac-hale-holo.jpg'),
  ('isaac-hale', 'signature', 'cards/isaac-hale-signature.jpg'),
  ('isaac-hale', 'legendaire', 'cards/isaac-hale-legendaire.jpg'),
  ('jinjer', 'commune', 'cards/jinjer-commune.jpg'),
  ('jinjer', 'rare', 'cards/jinjer-rare.jpg'),
  ('jinjer', 'holo', 'cards/jinjer-holo.jpg'),
  ('jinjer', 'signature', 'cards/jinjer-signature.jpg'),
  ('jinjer', 'legendaire', 'cards/jinjer-legendaire.jpg'),
  ('spiritbox', 'commune', 'cards/spiritbox-commune.jpg'),
  ('spiritbox', 'rare', 'cards/spiritbox-rare.jpg'),
  ('spiritbox', 'holo', 'cards/spiritbox-holo.jpg'),
  ('spiritbox', 'signature', 'cards/spiritbox-signature.jpg'),
  ('spiritbox', 'legendaire', 'cards/spiritbox-legendaire.jpg'),
  ('landmvrks', 'commune', 'cards/landmvrks-commune.jpg'),
  ('landmvrks', 'rare', 'cards/landmvrks-rare.jpg'),
  ('landmvrks', 'holo', 'cards/landmvrks-holo.jpg'),
  ('landmvrks', 'signature', 'cards/landmvrks-signature.jpg'),
  ('landmvrks', 'legendaire', 'cards/landmvrks-legendaire.jpg'),
  ('ramos', 'commune', 'cards/ramos-commune.jpg'),
  ('ramos', 'rare', 'cards/ramos-rare.jpg'),
  ('ramos', 'holo', 'cards/ramos-holo.jpg'),
  ('ramos', 'signature', 'cards/ramos-signature.jpg'),
  ('ramos', 'legendaire', 'cards/ramos-legendaire.jpg'),
  ('heriot', 'commune', 'cards/heriot-commune.jpg'),
  ('heriot', 'rare', 'cards/heriot-rare.jpg'),
  ('heriot', 'holo', 'cards/heriot-holo.jpg'),
  ('heriot', 'signature', 'cards/heriot-signature.jpg'),
  ('heriot', 'legendaire', 'cards/heriot-legendaire.jpg'),
  ('duplantier', 'commune', 'cards/duplantier-commune.jpg'),
  ('duplantier', 'rare', 'cards/duplantier-rare.jpg'),
  ('duplantier', 'holo', 'cards/duplantier-holo.jpg'),
  ('duplantier', 'signature', 'cards/duplantier-signature.jpg'),
  ('duplantier', 'legendaire', 'cards/duplantier-legendaire.jpg'),
  ('blink182', 'commune', 'cards/blink182-commune.jpg'),
  ('blink182', 'rare', 'cards/blink182-rare.jpg'),
  ('blink182', 'holo', 'cards/blink182-holo.jpg'),
  ('blink182', 'signature', 'cards/blink182-signature.jpg'),
  ('blink182', 'legendaire', 'cards/blink182-legendaire.jpg'),
  ('hoppus', 'commune', 'cards/hoppus-commune.jpg'),
  ('hoppus', 'rare', 'cards/hoppus-rare.jpg'),
  ('hoppus', 'holo', 'cards/hoppus-holo.jpg'),
  ('hoppus', 'signature', 'cards/hoppus-signature.jpg'),
  ('hoppus', 'legendaire', 'cards/hoppus-legendaire.jpg'),
  ('hendrix', 'commune', 'cards/hendrix-commune.jpg'),
  ('hendrix', 'rare', 'cards/hendrix-rare.jpg'),
  ('hendrix', 'holo', 'cards/hendrix-holo.jpg'),
  ('hendrix', 'signature', 'cards/hendrix-signature.jpg'),
  ('hendrix', 'legendaire', 'cards/hendrix-legendaire.jpg'),
  ('korn', 'commune', 'cards/korn-commune.jpg'),
  ('korn', 'rare', 'cards/korn-rare.jpg'),
  ('korn', 'holo', 'cards/korn-holo.jpg'),
  ('korn', 'signature', 'cards/korn-signature.jpg'),
  ('korn', 'legendaire', 'cards/korn-legendaire.jpg'),
  ('poppy', 'commune', 'cards/poppy-commune.jpg'),
  ('poppy', 'rare', 'cards/poppy-rare.jpg'),
  ('poppy', 'holo', 'cards/poppy-holo.jpg'),
  ('poppy', 'signature', 'cards/poppy-signature.jpg'),
  ('poppy', 'legendaire', 'cards/poppy-legendaire.jpg'),
  ('slash', 'commune', 'cards/slash-commune.jpg'),
  ('slash', 'rare', 'cards/slash-rare.jpg'),
  ('slash', 'holo', 'cards/slash-holo.jpg'),
  ('slash', 'signature', 'cards/slash-signature.jpg'),
  ('slash', 'legendaire', 'cards/slash-legendaire.jpg'),
  ('zack', 'commune', 'cards/zack-commune.jpg'),
  ('zack', 'rare', 'cards/zack-rare.jpg'),
  ('zack', 'holo', 'cards/zack-holo.jpg'),
  ('zack', 'signature', 'cards/zack-signature.jpg'),
  ('zack', 'legendaire', 'cards/zack-legendaire.jpg'),
  ('frusciante', 'commune', 'cards/frusciante-commune.jpg'),
  ('frusciante', 'rare', 'cards/frusciante-rare.jpg'),
  ('frusciante', 'holo', 'cards/frusciante-holo.jpg'),
  ('frusciante', 'signature', 'cards/frusciante-signature.jpg'),
  ('frusciante', 'legendaire', 'cards/frusciante-legendaire.jpg'),
  ('root', 'commune', 'cards/root-commune.jpg'),
  ('root', 'rare', 'cards/root-rare.jpg'),
  ('root', 'holo', 'cards/root-holo.jpg'),
  ('root', 'signature', 'cards/root-signature.jpg'),
  ('root', 'legendaire', 'cards/root-legendaire.jpg'),
  ('jordison', 'commune', 'cards/jordison-commune.jpg'),
  ('jordison', 'rare', 'cards/jordison-rare.jpg'),
  ('jordison', 'holo', 'cards/jordison-holo.jpg'),
  ('jordison', 'signature', 'cards/jordison-signature.jpg'),
  ('jordison', 'legendaire', 'cards/jordison-legendaire.jpg')
on conflict do nothing;

insert into public.binders (id, kind, label, sort) values
  ('all', 'collection', 'Toutes les cartes', 0),
  ('metalcore', 'style', 'Metalcore', 1),
  ('hardcore', 'style', 'Hardcore & extrême', 2),
  ('numetal', 'style', 'Nu metal & alternatif', 3),
  ('poppunk', 'style', 'Pop punk', 4),
  ('legendes', 'style', 'Légendes du rock', 5),
  ('batteurs', 'instrument', 'Les batteurs', 6),
  ('guitaristes', 'instrument', 'Les guitaristes', 7),
  ('g-kl', 'band', 'Knocked Loose', 8),
  ('g-blink', 'band', 'Blink-182', 9),
  ('g-slipknot', 'band', 'Slipknot', 10)
on conflict (id) do nothing;

insert into public.binder_members (binder_id, musician_id) values
  ('all', 'knocked-loose'),
  ('all', 'isaac-hale'),
  ('all', 'jinjer'),
  ('all', 'spiritbox'),
  ('all', 'landmvrks'),
  ('all', 'ramos'),
  ('all', 'heriot'),
  ('all', 'duplantier'),
  ('all', 'blink182'),
  ('all', 'hoppus'),
  ('all', 'hendrix'),
  ('all', 'korn'),
  ('all', 'poppy'),
  ('all', 'slash'),
  ('all', 'zack'),
  ('all', 'frusciante'),
  ('all', 'root'),
  ('all', 'jordison'),
  ('metalcore', 'spiritbox'),
  ('metalcore', 'jinjer'),
  ('metalcore', 'landmvrks'),
  ('metalcore', 'heriot'),
  ('hardcore', 'knocked-loose'),
  ('hardcore', 'isaac-hale'),
  ('hardcore', 'ramos'),
  ('hardcore', 'duplantier'),
  ('numetal', 'korn'),
  ('numetal', 'root'),
  ('numetal', 'jordison'),
  ('numetal', 'zack'),
  ('numetal', 'poppy'),
  ('poppunk', 'blink182'),
  ('poppunk', 'hoppus'),
  ('legendes', 'hendrix'),
  ('legendes', 'slash'),
  ('legendes', 'frusciante'),
  ('batteurs', 'blink182'),
  ('batteurs', 'duplantier'),
  ('batteurs', 'jordison'),
  ('guitaristes', 'isaac-hale'),
  ('guitaristes', 'hendrix'),
  ('guitaristes', 'slash'),
  ('guitaristes', 'frusciante'),
  ('guitaristes', 'root'),
  ('g-kl', 'knocked-loose'),
  ('g-kl', 'isaac-hale'),
  ('g-blink', 'blink182'),
  ('g-blink', 'hoppus'),
  ('g-slipknot', 'root'),
  ('g-slipknot', 'jordison')
on conflict do nothing;

insert into public.pack_types (id, label, size, binder_id) values
  ('mosh', 'Mosh Pack', 5, null),
  ('metalcore', 'Metalcore', 5, 'metalcore'),
  ('hardcore', 'Hardcore & extrême', 5, 'hardcore'),
  ('numetal', 'Nu metal & alternatif', 5, 'numetal'),
  ('poppunk', 'Pop punk', 5, 'poppunk'),
  ('legendes', 'Légendes du rock', 5, 'legendes')
on conflict (id) do nothing;

insert into public.pack_odds (pack_type_id, rarity, weight) values
  ('mosh', 'commune', 60),
  ('mosh', 'rare', 25),
  ('mosh', 'holo', 10),
  ('mosh', 'signature', 4),
  ('mosh', 'legendaire', 1),
  ('metalcore', 'commune', 60),
  ('metalcore', 'rare', 25),
  ('metalcore', 'holo', 10),
  ('metalcore', 'signature', 4),
  ('metalcore', 'legendaire', 1),
  ('hardcore', 'commune', 60),
  ('hardcore', 'rare', 25),
  ('hardcore', 'holo', 10),
  ('hardcore', 'signature', 4),
  ('hardcore', 'legendaire', 1),
  ('numetal', 'commune', 60),
  ('numetal', 'rare', 25),
  ('numetal', 'holo', 10),
  ('numetal', 'signature', 4),
  ('numetal', 'legendaire', 1),
  ('poppunk', 'commune', 60),
  ('poppunk', 'rare', 25),
  ('poppunk', 'holo', 10),
  ('poppunk', 'signature', 4),
  ('poppunk', 'legendaire', 1),
  ('legendes', 'commune', 60),
  ('legendes', 'rare', 25),
  ('legendes', 'holo', 10),
  ('legendes', 'signature', 4),
  ('legendes', 'legendaire', 1)
on conflict do nothing;

insert into public.settings (key, value) values
  ('fusion_cost', '5'),
  ('packs_per_day', '20')
on conflict (key) do nothing;

commit;
