-- Généré par tools/gen_seed.py depuis Catalog.swift : ne pas modifier à la main.
begin;

insert into public.musicians (id, name, band, arcana_title, arcana_number, instruments, subgenre) values
  ('knocked-loose', 'Bryan Garris', 'Knocked Loose', 'The Deadringer', 'IV', array['chant']::text[], 'Hardcore'),
  ('isaac-hale', 'Isaac Hale', 'Knocked Loose', 'Counting Worms', 'X', array['guitare']::text[], 'Hardcore'),
  ('jinjer', 'Tatiana Shmayluk', 'Jinjer', 'Pisces', 'V', array['chant']::text[], 'Metalcore progressif'),
  ('spiritbox', 'Courtney LaPlante', 'Spiritbox', 'Holy Roller', 'VI', array['chant']::text[], 'Metalcore'),
  ('landmvrks', 'Florent Salfati', 'Landmvrks', 'Lost in the Waves', 'VIII', array['chant']::text[], 'Metalcore'),
  ('ramos', 'Will Ramos', 'Lorna Shore', 'To the Hellfire', 'XIV', array['chant']::text[], 'Deathcore'),
  ('heriot', 'Debbie Gough', 'Heriot', 'Devoured by the Mouth of Hell', 'XVIII', array['chant', 'guitare']::text[], 'Metalcore'),
  ('duplantier', 'Mario Duplantier', 'Gojira', 'Flying Whales', 'XVI', array['batterie']::text[], 'Death metal progressif'),
  ('blink182', 'Travis Barker', 'Blink-182', 'All the Small Things', 'VII', array['batterie']::text[], 'Pop punk'),
  ('hoppus', 'Mark Hoppus', 'Blink-182', 'What''s My Age Again?', 'XII', array['basse', 'chant']::text[], 'Pop punk'),
  ('hendrix', 'Jimi Hendrix', 'Jimi Hendrix', 'Purple Haze', 'IX', array['guitare']::text[], 'Rock psychédélique'),
  ('korn', 'Jonathan Davis', 'Korn', 'Freak on a Leash', 'XI', array['chant']::text[], 'Nu metal'),
  ('poppy', 'Poppy', 'Poppy', 'I Disagree', 'XIII', array['chant']::text[], 'Métal expérimental'),
  ('slash', 'Slash', 'Guns N'' Roses', 'Welcome to the Jungle', 'XV', array['guitare']::text[], 'Hard rock'),
  ('zack', 'Zack de la Rocha', 'Rage Against the Machine', 'Bulls on Parade', 'XVII', array['chant']::text[], 'Rap metal'),
  ('frusciante', 'John Frusciante', 'Red Hot Chili Peppers', 'Under the Bridge', 'XIX', array['guitare']::text[], 'Funk rock'),
  ('root', 'Jim Root', 'Slipknot', 'Duality', 'XX', array['guitare']::text[], 'Nu metal'),
  ('jordison', 'Joey Jordison', 'Slipknot', 'Wait and Bleed', 'XXI', array['batterie']::text[], 'Nu metal'),
  ('dickinson', 'Bruce Dickinson', 'Iron Maiden', 'The Trooper', 'XXII', array['chant']::text[], 'Heavy metal'),
  ('halford', 'Rob Halford', 'Judas Priest', 'Breaking the Law', 'XXIII', array['chant']::text[], 'Heavy metal'),
  ('ozzy', 'Ozzy Osbourne', 'Black Sabbath', 'Paranoid', 'XXIV', array['chant']::text[], 'Heavy metal'),
  ('lemmy', 'Lemmy Kilmister', 'Motörhead', 'Ace of Spades', 'XXV', array['basse', 'chant']::text[], 'Heavy metal'),
  ('hetfield', 'James Hetfield', 'Metallica', 'Master of Puppets', 'XXVI', array['chant', 'guitare']::text[], 'Thrash metal'),
  ('mustaine', 'Dave Mustaine', 'Megadeth', 'Symphony of Destruction', 'XXVII', array['guitare', 'chant']::text[], 'Thrash metal'),
  ('araya', 'Tom Araya', 'Slayer', 'Raining Blood', 'XXVIII', array['basse', 'chant']::text[], 'Thrash metal'),
  ('scott-ian', 'Scott Ian', 'Anthrax', 'Madhouse', 'XXIX', array['guitare']::text[], 'Thrash metal'),
  ('cobain', 'Kurt Cobain', 'Nirvana', 'Smells Like Teen Spirit', 'XXX', array['chant', 'guitare']::text[], 'Grunge'),
  ('cornell', 'Chris Cornell', 'Soundgarden', 'Black Hole Sun', 'XXXI', array['chant']::text[], 'Grunge'),
  ('staley', 'Layne Staley', 'Alice in Chains', 'Man in the Box', 'XXXII', array['chant']::text[], 'Grunge'),
  ('grohl', 'Dave Grohl', 'Foo Fighters', 'Everlong', 'XXXIII', array['chant', 'guitare']::text[], 'Rock alternatif'),
  ('keenan', 'Maynard James Keenan', 'Tool', 'Schism', 'XXXIV', array['chant']::text[], 'Metal progressif'),
  ('white-gluz', 'Alissa White-Gluz', 'Arch Enemy', 'The Eagle Flies Alone', 'XXXV', array['chant']::text[], 'Death metal mélodique'),
  ('corpsegrinder', 'George Fisher', 'Cannibal Corpse', 'Hammer Smashed Face', 'XXXVI', array['chant']::text[], 'Death metal'),
  ('tankian', 'Serj Tankian', 'System of a Down', 'Toxicity', 'XXXVII', array['chant']::text[], 'Metal alternatif'),
  ('sykes', 'Oli Sykes', 'Bring Me the Horizon', 'Throne', 'XXXVIII', array['chant']::text[], 'Metalcore'),
  ('hayley', 'Hayley Williams', 'Paramore', 'Misery Business', 'XXXIX', array['chant']::text[], 'Pop punk'),
  ('armstrong', 'Billie Joe Armstrong', 'Green Day', 'Boulevard of Broken Dreams', 'XL', array['chant', 'guitare']::text[], 'Punk rock'),
  ('angus', 'Angus Young', 'AC/DC', 'Highway to Hell', 'XLI', array['guitare']::text[], 'Hard rock'),
  ('dio', 'Ronnie James Dio', 'Dio', 'Holy Diver', 'XLII', array['chant']::text[], 'Heavy metal'),
  ('doro', 'Doro Pesch', 'Warlock', 'All We Are', 'XLIII', array['chant']::text[], 'Heavy metal'),
  ('hammett', 'Kirk Hammett', 'Metallica', 'Enter Sandman', 'XLIV', array['guitare']::text[], 'Thrash metal'),
  ('mercury', 'Freddie Mercury', 'Queen', 'Bohemian Rhapsody', 'XLV', array['chant']::text[], 'Rock'),
  ('gerard-way', 'Gerard Way', 'My Chemical Romance', 'Welcome to the Black Parade', 'XLVI', array['chant']::text[], 'Emo')
on conflict (id) do nothing;

insert into public.cards (musician_id, rarity, image_path) values
  ('knocked-loose', 'commune', 'cards/knocked-loose-commune.jpg'),
  ('knocked-loose', 'rare', 'cards/knocked-loose-rare.jpg'),
  ('knocked-loose', 'holo', 'cards/knocked-loose-holo.jpg'),
  ('knocked-loose', 'signature', 'cards/knocked-loose-signature.jpg'),
  ('knocked-loose', 'legendaire', 'cards/knocked-loose-legendaire.jpg'),
  ('isaac-hale', 'commune', 'cards/isaac-hale-commune.jpg'),
  ('isaac-hale', 'rare', 'cards/isaac-hale-rare.jpg'),
  ('isaac-hale', 'holo', 'cards/isaac-hale-holo.jpg'),
  ('isaac-hale', 'signature', 'cards/isaac-hale-signature.jpg'),
  ('isaac-hale', 'legendaire', 'cards/isaac-hale-legendaire.jpg'),
  ('jinjer', 'commune', 'cards/jinjer-commune.jpg'),
  ('jinjer', 'rare', 'cards/jinjer-rare.jpg'),
  ('jinjer', 'holo', 'cards/jinjer-holo.jpg'),
  ('jinjer', 'signature', 'cards/jinjer-signature.jpg'),
  ('jinjer', 'legendaire', 'cards/jinjer-legendaire.jpg'),
  ('spiritbox', 'commune', 'cards/spiritbox-commune.jpg'),
  ('spiritbox', 'rare', 'cards/spiritbox-rare.jpg'),
  ('spiritbox', 'holo', 'cards/spiritbox-holo.jpg'),
  ('spiritbox', 'signature', 'cards/spiritbox-signature.jpg'),
  ('spiritbox', 'legendaire', 'cards/spiritbox-legendaire.jpg'),
  ('landmvrks', 'commune', 'cards/landmvrks-commune.jpg'),
  ('landmvrks', 'rare', 'cards/landmvrks-rare.jpg'),
  ('landmvrks', 'holo', 'cards/landmvrks-holo.jpg'),
  ('landmvrks', 'signature', 'cards/landmvrks-signature.jpg'),
  ('landmvrks', 'legendaire', 'cards/landmvrks-legendaire.jpg'),
  ('ramos', 'commune', 'cards/ramos-commune.jpg'),
  ('ramos', 'rare', 'cards/ramos-rare.jpg'),
  ('ramos', 'holo', 'cards/ramos-holo.jpg'),
  ('ramos', 'signature', 'cards/ramos-signature.jpg'),
  ('ramos', 'legendaire', 'cards/ramos-legendaire.jpg'),
  ('heriot', 'commune', 'cards/heriot-commune.jpg'),
  ('heriot', 'rare', 'cards/heriot-rare.jpg'),
  ('heriot', 'holo', 'cards/heriot-holo.jpg'),
  ('heriot', 'signature', 'cards/heriot-signature.jpg'),
  ('heriot', 'legendaire', 'cards/heriot-legendaire.jpg'),
  ('duplantier', 'commune', 'cards/duplantier-commune.jpg'),
  ('duplantier', 'rare', 'cards/duplantier-rare.jpg'),
  ('duplantier', 'holo', 'cards/duplantier-holo.jpg'),
  ('duplantier', 'signature', 'cards/duplantier-signature.jpg'),
  ('duplantier', 'legendaire', 'cards/duplantier-legendaire.jpg'),
  ('blink182', 'commune', 'cards/blink182-commune.jpg'),
  ('blink182', 'rare', 'cards/blink182-rare.jpg'),
  ('blink182', 'holo', 'cards/blink182-holo.jpg'),
  ('blink182', 'signature', 'cards/blink182-signature.jpg'),
  ('blink182', 'legendaire', 'cards/blink182-legendaire.jpg'),
  ('hoppus', 'commune', 'cards/hoppus-commune.jpg'),
  ('hoppus', 'rare', 'cards/hoppus-rare.jpg'),
  ('hoppus', 'holo', 'cards/hoppus-holo.jpg'),
  ('hoppus', 'signature', 'cards/hoppus-signature.jpg'),
  ('hoppus', 'legendaire', 'cards/hoppus-legendaire.jpg'),
  ('hendrix', 'commune', 'cards/hendrix-commune.jpg'),
  ('hendrix', 'rare', 'cards/hendrix-rare.jpg'),
  ('hendrix', 'holo', 'cards/hendrix-holo.jpg'),
  ('hendrix', 'signature', 'cards/hendrix-signature.jpg'),
  ('hendrix', 'legendaire', 'cards/hendrix-legendaire.jpg'),
  ('korn', 'commune', 'cards/korn-commune.jpg'),
  ('korn', 'rare', 'cards/korn-rare.jpg'),
  ('korn', 'holo', 'cards/korn-holo.jpg'),
  ('korn', 'signature', 'cards/korn-signature.jpg'),
  ('korn', 'legendaire', 'cards/korn-legendaire.jpg'),
  ('poppy', 'commune', 'cards/poppy-commune.jpg'),
  ('poppy', 'rare', 'cards/poppy-rare.jpg'),
  ('poppy', 'holo', 'cards/poppy-holo.jpg'),
  ('poppy', 'signature', 'cards/poppy-signature.jpg'),
  ('poppy', 'legendaire', 'cards/poppy-legendaire.jpg'),
  ('slash', 'commune', 'cards/slash-commune.jpg'),
  ('slash', 'rare', 'cards/slash-rare.jpg'),
  ('slash', 'holo', 'cards/slash-holo.jpg'),
  ('slash', 'signature', 'cards/slash-signature.jpg'),
  ('slash', 'legendaire', 'cards/slash-legendaire.jpg'),
  ('zack', 'commune', 'cards/zack-commune.jpg'),
  ('zack', 'rare', 'cards/zack-rare.jpg'),
  ('zack', 'holo', 'cards/zack-holo.jpg'),
  ('zack', 'signature', 'cards/zack-signature.jpg'),
  ('zack', 'legendaire', 'cards/zack-legendaire.jpg'),
  ('frusciante', 'commune', 'cards/frusciante-commune.jpg'),
  ('frusciante', 'rare', 'cards/frusciante-rare.jpg'),
  ('frusciante', 'holo', 'cards/frusciante-holo.jpg'),
  ('frusciante', 'signature', 'cards/frusciante-signature.jpg'),
  ('frusciante', 'legendaire', 'cards/frusciante-legendaire.jpg'),
  ('root', 'commune', 'cards/root-commune.jpg'),
  ('root', 'rare', 'cards/root-rare.jpg'),
  ('root', 'holo', 'cards/root-holo.jpg'),
  ('root', 'signature', 'cards/root-signature.jpg'),
  ('root', 'legendaire', 'cards/root-legendaire.jpg'),
  ('jordison', 'commune', 'cards/jordison-commune.jpg'),
  ('jordison', 'rare', 'cards/jordison-rare.jpg'),
  ('jordison', 'holo', 'cards/jordison-holo.jpg'),
  ('jordison', 'signature', 'cards/jordison-signature.jpg'),
  ('jordison', 'legendaire', 'cards/jordison-legendaire.jpg'),
  ('dickinson', 'commune', 'cards/dickinson-commune.jpg'),
  ('dickinson', 'rare', 'cards/dickinson-rare.jpg'),
  ('dickinson', 'holo', 'cards/dickinson-holo.jpg'),
  ('dickinson', 'signature', 'cards/dickinson-signature.jpg'),
  ('dickinson', 'legendaire', 'cards/dickinson-legendaire.jpg'),
  ('halford', 'commune', 'cards/halford-commune.jpg'),
  ('halford', 'rare', 'cards/halford-rare.jpg'),
  ('halford', 'holo', 'cards/halford-holo.jpg'),
  ('halford', 'signature', 'cards/halford-signature.jpg'),
  ('halford', 'legendaire', 'cards/halford-legendaire.jpg'),
  ('ozzy', 'commune', 'cards/ozzy-commune.jpg'),
  ('ozzy', 'rare', 'cards/ozzy-rare.jpg'),
  ('ozzy', 'holo', 'cards/ozzy-holo.jpg'),
  ('ozzy', 'signature', 'cards/ozzy-signature.jpg'),
  ('ozzy', 'legendaire', 'cards/ozzy-legendaire.jpg'),
  ('lemmy', 'commune', 'cards/lemmy-commune.jpg'),
  ('lemmy', 'rare', 'cards/lemmy-rare.jpg'),
  ('lemmy', 'holo', 'cards/lemmy-holo.jpg'),
  ('lemmy', 'signature', 'cards/lemmy-signature.jpg'),
  ('lemmy', 'legendaire', 'cards/lemmy-legendaire.jpg'),
  ('hetfield', 'commune', 'cards/hetfield-commune.jpg'),
  ('hetfield', 'rare', 'cards/hetfield-rare.jpg'),
  ('hetfield', 'holo', 'cards/hetfield-holo.jpg'),
  ('hetfield', 'signature', 'cards/hetfield-signature.jpg'),
  ('hetfield', 'legendaire', 'cards/hetfield-legendaire.jpg'),
  ('mustaine', 'commune', 'cards/mustaine-commune.jpg'),
  ('mustaine', 'rare', 'cards/mustaine-rare.jpg'),
  ('mustaine', 'holo', 'cards/mustaine-holo.jpg'),
  ('mustaine', 'signature', 'cards/mustaine-signature.jpg'),
  ('mustaine', 'legendaire', 'cards/mustaine-legendaire.jpg'),
  ('araya', 'commune', 'cards/araya-commune.jpg'),
  ('araya', 'rare', 'cards/araya-rare.jpg'),
  ('araya', 'holo', 'cards/araya-holo.jpg'),
  ('araya', 'signature', 'cards/araya-signature.jpg'),
  ('araya', 'legendaire', 'cards/araya-legendaire.jpg'),
  ('scott-ian', 'commune', 'cards/scott-ian-commune.jpg'),
  ('scott-ian', 'rare', 'cards/scott-ian-rare.jpg'),
  ('scott-ian', 'holo', 'cards/scott-ian-holo.jpg'),
  ('scott-ian', 'signature', 'cards/scott-ian-signature.jpg'),
  ('scott-ian', 'legendaire', 'cards/scott-ian-legendaire.jpg'),
  ('cobain', 'commune', 'cards/cobain-commune.jpg'),
  ('cobain', 'rare', 'cards/cobain-rare.jpg'),
  ('cobain', 'holo', 'cards/cobain-holo.jpg'),
  ('cobain', 'signature', 'cards/cobain-signature.jpg'),
  ('cobain', 'legendaire', 'cards/cobain-legendaire.jpg'),
  ('cornell', 'commune', 'cards/cornell-commune.jpg'),
  ('cornell', 'rare', 'cards/cornell-rare.jpg'),
  ('cornell', 'holo', 'cards/cornell-holo.jpg'),
  ('cornell', 'signature', 'cards/cornell-signature.jpg'),
  ('cornell', 'legendaire', 'cards/cornell-legendaire.jpg'),
  ('staley', 'commune', 'cards/staley-commune.jpg'),
  ('staley', 'rare', 'cards/staley-rare.jpg'),
  ('staley', 'holo', 'cards/staley-holo.jpg'),
  ('staley', 'signature', 'cards/staley-signature.jpg'),
  ('staley', 'legendaire', 'cards/staley-legendaire.jpg'),
  ('grohl', 'commune', 'cards/grohl-commune.jpg'),
  ('grohl', 'rare', 'cards/grohl-rare.jpg'),
  ('grohl', 'holo', 'cards/grohl-holo.jpg'),
  ('grohl', 'signature', 'cards/grohl-signature.jpg'),
  ('grohl', 'legendaire', 'cards/grohl-legendaire.jpg'),
  ('keenan', 'commune', 'cards/keenan-commune.jpg'),
  ('keenan', 'rare', 'cards/keenan-rare.jpg'),
  ('keenan', 'holo', 'cards/keenan-holo.jpg'),
  ('keenan', 'signature', 'cards/keenan-signature.jpg'),
  ('keenan', 'legendaire', 'cards/keenan-legendaire.jpg'),
  ('white-gluz', 'commune', 'cards/white-gluz-commune.jpg'),
  ('white-gluz', 'rare', 'cards/white-gluz-rare.jpg'),
  ('white-gluz', 'holo', 'cards/white-gluz-holo.jpg'),
  ('white-gluz', 'signature', 'cards/white-gluz-signature.jpg'),
  ('white-gluz', 'legendaire', 'cards/white-gluz-legendaire.jpg'),
  ('corpsegrinder', 'commune', 'cards/corpsegrinder-commune.jpg'),
  ('corpsegrinder', 'rare', 'cards/corpsegrinder-rare.jpg'),
  ('corpsegrinder', 'holo', 'cards/corpsegrinder-holo.jpg'),
  ('corpsegrinder', 'signature', 'cards/corpsegrinder-signature.jpg'),
  ('corpsegrinder', 'legendaire', 'cards/corpsegrinder-legendaire.jpg'),
  ('tankian', 'commune', 'cards/tankian-commune.jpg'),
  ('tankian', 'rare', 'cards/tankian-rare.jpg'),
  ('tankian', 'holo', 'cards/tankian-holo.jpg'),
  ('tankian', 'signature', 'cards/tankian-signature.jpg'),
  ('tankian', 'legendaire', 'cards/tankian-legendaire.jpg'),
  ('sykes', 'commune', 'cards/sykes-commune.jpg'),
  ('sykes', 'rare', 'cards/sykes-rare.jpg'),
  ('sykes', 'holo', 'cards/sykes-holo.jpg'),
  ('sykes', 'signature', 'cards/sykes-signature.jpg'),
  ('sykes', 'legendaire', 'cards/sykes-legendaire.jpg'),
  ('hayley', 'commune', 'cards/hayley-commune.jpg'),
  ('hayley', 'rare', 'cards/hayley-rare.jpg'),
  ('hayley', 'holo', 'cards/hayley-holo.jpg'),
  ('hayley', 'signature', 'cards/hayley-signature.jpg'),
  ('hayley', 'legendaire', 'cards/hayley-legendaire.jpg'),
  ('armstrong', 'commune', 'cards/armstrong-commune.jpg'),
  ('armstrong', 'rare', 'cards/armstrong-rare.jpg'),
  ('armstrong', 'holo', 'cards/armstrong-holo.jpg'),
  ('armstrong', 'signature', 'cards/armstrong-signature.jpg'),
  ('armstrong', 'legendaire', 'cards/armstrong-legendaire.jpg'),
  ('angus', 'commune', 'cards/angus-commune.jpg'),
  ('angus', 'rare', 'cards/angus-rare.jpg'),
  ('angus', 'holo', 'cards/angus-holo.jpg'),
  ('angus', 'signature', 'cards/angus-signature.jpg'),
  ('angus', 'legendaire', 'cards/angus-legendaire.jpg'),
  ('dio', 'commune', 'cards/dio-commune.jpg'),
  ('dio', 'rare', 'cards/dio-rare.jpg'),
  ('dio', 'holo', 'cards/dio-holo.jpg'),
  ('dio', 'signature', 'cards/dio-signature.jpg'),
  ('dio', 'legendaire', 'cards/dio-legendaire.jpg'),
  ('doro', 'commune', 'cards/doro-commune.jpg'),
  ('doro', 'rare', 'cards/doro-rare.jpg'),
  ('doro', 'holo', 'cards/doro-holo.jpg'),
  ('doro', 'signature', 'cards/doro-signature.jpg'),
  ('doro', 'legendaire', 'cards/doro-legendaire.jpg'),
  ('hammett', 'commune', 'cards/hammett-commune.jpg'),
  ('hammett', 'rare', 'cards/hammett-rare.jpg'),
  ('hammett', 'holo', 'cards/hammett-holo.jpg'),
  ('hammett', 'signature', 'cards/hammett-signature.jpg'),
  ('hammett', 'legendaire', 'cards/hammett-legendaire.jpg'),
  ('mercury', 'commune', 'cards/mercury-commune.jpg'),
  ('mercury', 'rare', 'cards/mercury-rare.jpg'),
  ('mercury', 'holo', 'cards/mercury-holo.jpg'),
  ('mercury', 'signature', 'cards/mercury-signature.jpg'),
  ('mercury', 'legendaire', 'cards/mercury-legendaire.jpg'),
  ('gerard-way', 'commune', 'cards/gerard-way-commune.jpg'),
  ('gerard-way', 'rare', 'cards/gerard-way-rare.jpg'),
  ('gerard-way', 'holo', 'cards/gerard-way-holo.jpg'),
  ('gerard-way', 'signature', 'cards/gerard-way-signature.jpg'),
  ('gerard-way', 'legendaire', 'cards/gerard-way-legendaire.jpg')
on conflict do nothing;

insert into public.binders (id, kind, label, sort) values
  ('all', 'collection', 'Toutes les cartes', 0),
  ('metalcore', 'style', 'Metalcore', 1),
  ('hardcore', 'style', 'Hardcore & extrême', 2),
  ('numetal', 'style', 'Nu metal & alternatif', 3),
  ('poppunk', 'style', 'Pop punk', 4),
  ('legendes', 'style', 'Légendes du rock', 5),
  ('heavy', 'style', 'Heavy metal', 6),
  ('thrash', 'style', 'Thrash', 7),
  ('grunge', 'style', 'Grunge & alternatif', 8),
  ('batteurs', 'instrument', 'Les batteurs', 9),
  ('guitaristes', 'instrument', 'Les guitaristes', 10),
  ('bassistes', 'instrument', 'Les bassistes', 11),
  ('g-kl', 'band', 'Knocked Loose', 12),
  ('g-blink', 'band', 'Blink-182', 13),
  ('g-slipknot', 'band', 'Slipknot', 14)
on conflict (id) do nothing;

insert into public.binder_members (binder_id, musician_id) values
  ('all', 'knocked-loose'),
  ('all', 'isaac-hale'),
  ('all', 'jinjer'),
  ('all', 'spiritbox'),
  ('all', 'landmvrks'),
  ('all', 'ramos'),
  ('all', 'heriot'),
  ('all', 'duplantier'),
  ('all', 'blink182'),
  ('all', 'hoppus'),
  ('all', 'hendrix'),
  ('all', 'korn'),
  ('all', 'poppy'),
  ('all', 'slash'),
  ('all', 'zack'),
  ('all', 'frusciante'),
  ('all', 'root'),
  ('all', 'jordison'),
  ('all', 'dickinson'),
  ('all', 'halford'),
  ('all', 'ozzy'),
  ('all', 'lemmy'),
  ('all', 'hetfield'),
  ('all', 'mustaine'),
  ('all', 'araya'),
  ('all', 'scott-ian'),
  ('all', 'cobain'),
  ('all', 'cornell'),
  ('all', 'staley'),
  ('all', 'grohl'),
  ('all', 'keenan'),
  ('all', 'white-gluz'),
  ('all', 'corpsegrinder'),
  ('all', 'tankian'),
  ('all', 'sykes'),
  ('all', 'hayley'),
  ('all', 'armstrong'),
  ('all', 'angus'),
  ('all', 'dio'),
  ('all', 'doro'),
  ('all', 'hammett'),
  ('all', 'mercury'),
  ('all', 'gerard-way'),
  ('metalcore', 'spiritbox'),
  ('metalcore', 'jinjer'),
  ('metalcore', 'landmvrks'),
  ('metalcore', 'heriot'),
  ('metalcore', 'sykes'),
  ('hardcore', 'knocked-loose'),
  ('hardcore', 'isaac-hale'),
  ('hardcore', 'ramos'),
  ('hardcore', 'duplantier'),
  ('hardcore', 'white-gluz'),
  ('hardcore', 'corpsegrinder'),
  ('numetal', 'korn'),
  ('numetal', 'root'),
  ('numetal', 'jordison'),
  ('numetal', 'zack'),
  ('numetal', 'poppy'),
  ('numetal', 'tankian'),
  ('poppunk', 'blink182'),
  ('poppunk', 'hoppus'),
  ('poppunk', 'hayley'),
  ('poppunk', 'armstrong'),
  ('poppunk', 'gerard-way'),
  ('legendes', 'hendrix'),
  ('legendes', 'slash'),
  ('legendes', 'frusciante'),
  ('legendes', 'angus'),
  ('legendes', 'mercury'),
  ('heavy', 'dickinson'),
  ('heavy', 'halford'),
  ('heavy', 'ozzy'),
  ('heavy', 'lemmy'),
  ('heavy', 'dio'),
  ('heavy', 'doro'),
  ('thrash', 'hetfield'),
  ('thrash', 'mustaine'),
  ('thrash', 'araya'),
  ('thrash', 'scott-ian'),
  ('thrash', 'hammett'),
  ('grunge', 'cobain'),
  ('grunge', 'cornell'),
  ('grunge', 'staley'),
  ('grunge', 'grohl'),
  ('grunge', 'keenan'),
  ('batteurs', 'blink182'),
  ('batteurs', 'duplantier'),
  ('batteurs', 'jordison'),
  ('guitaristes', 'isaac-hale'),
  ('guitaristes', 'hendrix'),
  ('guitaristes', 'slash'),
  ('guitaristes', 'frusciante'),
  ('guitaristes', 'root'),
  ('guitaristes', 'mustaine'),
  ('guitaristes', 'scott-ian'),
  ('guitaristes', 'angus'),
  ('guitaristes', 'hammett'),
  ('bassistes', 'hoppus'),
  ('bassistes', 'lemmy'),
  ('bassistes', 'araya'),
  ('g-kl', 'knocked-loose'),
  ('g-kl', 'isaac-hale'),
  ('g-blink', 'blink182'),
  ('g-blink', 'hoppus'),
  ('g-slipknot', 'root'),
  ('g-slipknot', 'jordison')
on conflict do nothing;

insert into public.pack_types (id, label, size, binder_id) values
  ('mosh', 'Mosh Pack', 5, null),
  ('metalcore', 'Metalcore', 5, 'metalcore'),
  ('hardcore', 'Hardcore & extrême', 5, 'hardcore'),
  ('numetal', 'Nu metal & alternatif', 5, 'numetal'),
  ('poppunk', 'Pop punk', 5, 'poppunk'),
  ('legendes', 'Légendes du rock', 5, 'legendes')
on conflict (id) do nothing;

insert into public.pack_odds (pack_type_id, rarity, weight) values
  ('mosh', 'commune', 60),
  ('mosh', 'rare', 25),
  ('mosh', 'holo', 10),
  ('mosh', 'signature', 4),
  ('mosh', 'legendaire', 1),
  ('metalcore', 'commune', 60),
  ('metalcore', 'rare', 25),
  ('metalcore', 'holo', 10),
  ('metalcore', 'signature', 4),
  ('metalcore', 'legendaire', 1),
  ('hardcore', 'commune', 60),
  ('hardcore', 'rare', 25),
  ('hardcore', 'holo', 10),
  ('hardcore', 'signature', 4),
  ('hardcore', 'legendaire', 1),
  ('numetal', 'commune', 60),
  ('numetal', 'rare', 25),
  ('numetal', 'holo', 10),
  ('numetal', 'signature', 4),
  ('numetal', 'legendaire', 1),
  ('poppunk', 'commune', 60),
  ('poppunk', 'rare', 25),
  ('poppunk', 'holo', 10),
  ('poppunk', 'signature', 4),
  ('poppunk', 'legendaire', 1),
  ('legendes', 'commune', 60),
  ('legendes', 'rare', 25),
  ('legendes', 'holo', 10),
  ('legendes', 'signature', 4),
  ('legendes', 'legendaire', 1)
on conflict do nothing;

insert into public.settings (key, value) values
  ('fusion_cost_commune', '3'),
  ('fusion_cost_rare', '6'),
  ('fusion_cost_holo', '12'),
  ('fusion_cost_signature', '24'),
  ('packs_per_day', '1')
on conflict (key) do nothing;

commit;
