-- Généré par tools/gen_seed.py depuis Catalog.swift : ne pas modifier à la main.
begin;

insert into public.musicians (id, name, band, arcana_title, arcana_number, instruments, subgenre) values
  ('knocked-loose', 'Bryan Garris', 'Knocked Loose', 'The Deadringer', 'IV', array['chant']::text[], 'Hardcore'),
  ('isaac-hale', 'Isaac Hale', 'Knocked Loose', 'Counting Worms', 'X', array['guitare']::text[], 'Hardcore'),
  ('jinjer', 'Tatiana Shmayluk', 'Jinjer', 'Pisces', 'V', array['chant']::text[], 'Metal progressif'),
  ('spiritbox', 'Courtney LaPlante', 'Spiritbox', 'Holy Roller', 'VI', array['chant']::text[], 'Metalcore'),
  ('landmvrks', 'Florent Salfati', 'Landmvrks', 'Lost in the Waves', 'VIII', array['chant']::text[], 'Metalcore'),
  ('ramos', 'Will Ramos', 'Lorna Shore', 'To the Hellfire', 'XIV', array['chant']::text[], 'Deathcore'),
  ('heriot', 'Debbie Gough', 'Heriot', 'Devoured by the Mouth of Hell', 'XVIII', array['chant', 'guitare']::text[], 'Metalcore'),
  ('duplantier', 'Mario Duplantier', 'Gojira', 'Flying Whales', 'XVI', array['batterie']::text[], 'Metal progressif'),
  ('blink182', 'Travis Barker', 'Blink-182', 'All the Small Things', 'VII', array['batterie']::text[], 'Pop punk'),
  ('hoppus', 'Mark Hoppus', 'Blink-182', 'What''s My Age Again?', 'XII', array['basse', 'chant']::text[], 'Pop punk'),
  ('hendrix', 'Jimi Hendrix', 'Jimi Hendrix', 'Purple Haze', 'IX', array['guitare']::text[], 'Rock psychédélique'),
  ('korn', 'Jonathan Davis', 'Korn', 'Freak on a Leash', 'XI', array['chant']::text[], 'Nu metal'),
  ('poppy', 'Poppy', 'Poppy', 'I Disagree', 'XIII', array['chant']::text[], 'Métal expérimental'),
  ('slash', 'Slash', 'Guns N'' Roses', 'Welcome to the Jungle', 'XV', array['guitare']::text[], 'Hard rock'),
  ('zack', 'Zack de la Rocha', 'Rage Against the Machine', 'Bulls on Parade', 'XVII', array['chant']::text[], 'Rap metal'),
  ('frusciante', 'John Frusciante', 'Red Hot Chili Peppers', 'Under the Bridge', 'XIX', array['guitare']::text[], 'Funk rock'),
  ('root', 'Jim Root', 'Slipknot', 'Duality', 'XX', array['guitare']::text[], 'Nu metal'),
  ('jordison', 'Joey Jordison', 'Slipknot', 'Wait and Bleed', 'XXI', array['batterie']::text[], 'Nu metal'),
  ('dickinson', 'Bruce Dickinson', 'Iron Maiden', 'The Trooper', 'XXII', array['chant']::text[], 'Heavy metal'),
  ('halford', 'Rob Halford', 'Judas Priest', 'Breaking the Law', 'XXIII', array['chant']::text[], 'Heavy metal'),
  ('ozzy', 'Ozzy Osbourne', 'Black Sabbath', 'Paranoid', 'XXIV', array['chant']::text[], 'Heavy metal'),
  ('lemmy', 'Lemmy Kilmister', 'Motörhead', 'Ace of Spades', 'XXV', array['basse', 'chant']::text[], 'Heavy metal'),
  ('hetfield', 'James Hetfield', 'Metallica', 'Master of Puppets', 'XXVI', array['chant', 'guitare']::text[], 'Thrash metal'),
  ('mustaine', 'Dave Mustaine', 'Megadeth', 'Symphony of Destruction', 'XXVII', array['guitare', 'chant']::text[], 'Thrash metal'),
  ('araya', 'Tom Araya', 'Slayer', 'Raining Blood', 'XXVIII', array['basse', 'chant']::text[], 'Thrash metal'),
  ('scott-ian', 'Scott Ian', 'Anthrax', 'Madhouse', 'XXIX', array['guitare']::text[], 'Thrash metal'),
  ('cobain', 'Kurt Cobain', 'Nirvana', 'Smells Like Teen Spirit', 'XXX', array['chant', 'guitare']::text[], 'Grunge'),
  ('cornell', 'Chris Cornell', 'Soundgarden', 'Black Hole Sun', 'XXXI', array['chant']::text[], 'Grunge'),
  ('staley', 'Layne Staley', 'Alice in Chains', 'Man in the Box', 'XXXII', array['chant']::text[], 'Grunge'),
  ('grohl', 'Dave Grohl', 'Foo Fighters', 'Everlong', 'XXXIII', array['chant', 'guitare']::text[], 'Rock alternatif'),
  ('keenan', 'Maynard James Keenan', 'Tool', 'Schism', 'XXXIV', array['chant']::text[], 'Metal progressif'),
  ('white-gluz', 'Alissa White-Gluz', 'Arch Enemy', 'The Eagle Flies Alone', 'XXXV', array['chant']::text[], 'Death metal mélodique'),
  ('corpsegrinder', 'George Fisher', 'Cannibal Corpse', 'Hammer Smashed Face', 'XXXVI', array['chant']::text[], 'Death metal'),
  ('tankian', 'Serj Tankian', 'System of a Down', 'Toxicity', 'XXXVII', array['chant']::text[], 'Metal alternatif'),
  ('sykes', 'Oli Sykes', 'Bring Me the Horizon', 'Throne', 'XXXVIII', array['chant']::text[], 'Metalcore'),
  ('hayley', 'Hayley Williams', 'Paramore', 'Misery Business', 'XXXIX', array['chant']::text[], 'Pop punk'),
  ('armstrong', 'Billie Joe Armstrong', 'Green Day', 'Boulevard of Broken Dreams', 'XL', array['chant', 'guitare']::text[], 'Punk rock'),
  ('angus', 'Angus Young', 'AC/DC', 'Highway to Hell', 'XLI', array['guitare']::text[], 'Hard rock'),
  ('dio', 'Ronnie James Dio', 'Dio', 'Holy Diver', 'XLII', array['chant']::text[], 'Heavy metal'),
  ('doro', 'Doro Pesch', 'Warlock', 'All We Are', 'XLIII', array['chant']::text[], 'Heavy metal'),
  ('hammett', 'Kirk Hammett', 'Metallica', 'Enter Sandman', 'XLIV', array['guitare']::text[], 'Thrash metal'),
  ('mercury', 'Freddie Mercury', 'Queen', 'Bohemian Rhapsody', 'XLV', array['chant']::text[], 'Rock'),
  ('gerard-way', 'Gerard Way', 'My Chemical Romance', 'Welcome to the Black Parade', 'XLVI', array['chant']::text[], 'Emo'),
  ('bennington', 'Chester Bennington', 'Linkin Park', 'Numb', 'XLVII', array['chant']::text[], 'Nu metal'),
  ('prince', 'Prince', 'Prince', 'Purple Rain', 'XLVIII', array['chant', 'guitare']::text[], 'Funk rock'),
  ('morello', 'Tom Morello', 'Rage Against the Machine', 'Killing in the Name', 'L', array['guitare']::text[], 'Rap metal'),
  ('lars', 'Lars Ulrich', 'Metallica', 'One', 'LI', array['batterie']::text[], 'Thrash metal'),
  ('burton', 'Cliff Burton', 'Metallica', 'Orion', 'LII', array['basse']::text[], 'Thrash metal'),
  ('lombardo', 'Dave Lombardo', 'Slayer', 'South of Heaven', 'LIII', array['batterie']::text[], 'Thrash metal'),
  ('harris', 'Steve Harris', 'Iron Maiden', 'Fear of the Dark', 'LIV', array['basse']::text[], 'Heavy metal'),
  ('iommi', 'Tony Iommi', 'Black Sabbath', 'Iron Man', 'LV', array['guitare']::text[], 'Heavy metal'),
  ('may', 'Brian May', 'Queen', 'We Will Rock You', 'LVI', array['guitare']::text[], 'Rock'),
  ('page', 'Jimmy Page', 'Led Zeppelin', 'Stairway to Heaven', 'LVII', array['guitare']::text[], 'Hard rock'),
  ('plant', 'Robert Plant', 'Led Zeppelin', 'Whole Lotta Love', 'LVIII', array['chant']::text[], 'Hard rock'),
  ('bonham', 'John Bonham', 'Led Zeppelin', 'Moby Dick', 'LIX', array['batterie']::text[], 'Hard rock'),
  ('flea', 'Flea', 'Red Hot Chili Peppers', 'Give It Away', 'LX', array['basse']::text[], 'Funk rock'),
  ('corey', 'Corey Taylor', 'Slipknot', 'Before I Forget', 'LXI', array['chant']::text[], 'Nu metal'),
  ('shinoda', 'Mike Shinoda', 'Linkin Park', 'In the End', 'LXII', array['chant', 'clavier']::text[], 'Nu metal'),
  ('malakian', 'Daron Malakian', 'System of a Down', 'Chop Suey!', 'LXIII', array['guitare', 'chant']::text[], 'Metal alternatif'),
  ('joe-duplantier', 'Joe Duplantier', 'Gojira', 'L''Enfant sauvage', 'LXIV', array['chant', 'guitare']::text[], 'Metal progressif'),
  ('amy-lee', 'Amy Lee', 'Evanescence', 'Bring Me to Life', 'LXV', array['chant']::text[], 'Metal gothique'),
  ('reuno', 'Reuno', 'Lofofora', 'Les gens', 'LXVI', array['chant']::text[], 'Metal fusion'),
  ('sam-carter', 'Sam Carter', 'Architects', 'Doomsday', 'LXVII', array['chant']::text[], 'Metalcore'),
  ('nito', 'Nito Mestre', 'Sui Generis', 'Canción para mi muerte', 'LXVIII', array['chant', 'guitare']::text[], 'Folk rock'),
  ('brendan-murphy', 'Brendan Murphy', 'Counterparts', 'Praise No Artery Intact', 'LXIX', array['chant']::text[], 'Hardcore mélodique'),
  ('chino', 'Chino Moreno', 'Deftones', 'Change', 'LXX', array['chant']::text[], 'Metal alternatif'),
  ('lzzy-hale', 'Lzzy Hale', 'Halestorm', 'I Miss the Misery', 'LXXI', array['chant', 'guitare']::text[], 'Hard rock'),
  ('peter-hayes', 'Peter Hayes', 'Black Rebel Motorcycle Club', 'Spread Your Love', 'LXXII', array['guitare', 'chant']::text[], 'Garage rock'),
  ('broden', 'Joakim Brodén', 'Sabaton', 'Primo Victoria', 'LXXIII', array['chant']::text[], 'Power metal'),
  ('mccall', 'Winston McCall', 'Parkway Drive', 'Wild Eyes', 'LXXIV', array['chant']::text[], 'Metalcore'),
  ('blythe', 'Randy Blythe', 'Lamb of God', 'Redneck', 'LXXV', array['chant']::text[], 'Groove metal'),
  ('heafy', 'Matt Heafy', 'Trivium', 'In Waves', 'LXXVI', array['chant', 'guitare']::text[], 'Metalcore'),
  ('kowalewicz', 'Ben Kowalewicz', 'Billy Talent', 'Red Flag', 'LXXVII', array['chant']::text[], 'Punk rock'),
  ('yates', 'Brendan Yates', 'Turnstile', 'Mystery', 'LXXVIII', array['chant']::text[], 'Hardcore'),
  ('honeycutt', 'Matt Honeycutt', 'Kublai Khan TX', 'Boomslang', 'LXXIX', array['chant']::text[], 'Beatdown hardcore'),
  ('flynn', 'Robb Flynn', 'Machine Head', 'Davidian', 'LXXX', array['chant', 'guitare']::text[], 'Groove metal')
on conflict (id) do update set name = excluded.name, band = excluded.band, arcana_title = excluded.arcana_title, arcana_number = excluded.arcana_number, instruments = excluded.instruments, subgenre = excluded.subgenre;

insert into public.cards (musician_id, rarity, image_path) values
  ('knocked-loose', 'commune', 'cards/knocked-loose-commune.jpg'),
  ('knocked-loose', 'rare', 'cards/knocked-loose-rare.jpg'),
  ('knocked-loose', 'holo', 'cards/knocked-loose-holo.jpg'),
  ('knocked-loose', 'signature', 'cards/knocked-loose-signature.jpg'),
  ('knocked-loose', 'legendaire', 'cards/knocked-loose-legendaire.jpg'),
  ('isaac-hale', 'commune', 'cards/isaac-hale-commune.jpg'),
  ('isaac-hale', 'rare', 'cards/isaac-hale-rare.jpg'),
  ('isaac-hale', 'holo', 'cards/isaac-hale-holo.jpg'),
  ('isaac-hale', 'signature', 'cards/isaac-hale-signature.jpg'),
  ('isaac-hale', 'legendaire', 'cards/isaac-hale-legendaire.jpg'),
  ('jinjer', 'commune', 'cards/jinjer-commune.jpg'),
  ('jinjer', 'rare', 'cards/jinjer-rare.jpg'),
  ('jinjer', 'holo', 'cards/jinjer-holo.jpg'),
  ('jinjer', 'signature', 'cards/jinjer-signature.jpg'),
  ('jinjer', 'legendaire', 'cards/jinjer-legendaire.jpg'),
  ('spiritbox', 'commune', 'cards/spiritbox-commune.jpg'),
  ('spiritbox', 'rare', 'cards/spiritbox-rare.jpg'),
  ('spiritbox', 'holo', 'cards/spiritbox-holo.jpg'),
  ('spiritbox', 'signature', 'cards/spiritbox-signature.jpg'),
  ('spiritbox', 'legendaire', 'cards/spiritbox-legendaire.jpg'),
  ('landmvrks', 'commune', 'cards/landmvrks-commune.jpg'),
  ('landmvrks', 'rare', 'cards/landmvrks-rare.jpg'),
  ('landmvrks', 'holo', 'cards/landmvrks-holo.jpg'),
  ('landmvrks', 'signature', 'cards/landmvrks-signature.jpg'),
  ('landmvrks', 'legendaire', 'cards/landmvrks-legendaire.jpg'),
  ('ramos', 'commune', 'cards/ramos-commune.jpg'),
  ('ramos', 'rare', 'cards/ramos-rare.jpg'),
  ('ramos', 'holo', 'cards/ramos-holo.jpg'),
  ('ramos', 'signature', 'cards/ramos-signature.jpg'),
  ('ramos', 'legendaire', 'cards/ramos-legendaire.jpg'),
  ('heriot', 'commune', 'cards/heriot-commune.jpg'),
  ('heriot', 'rare', 'cards/heriot-rare.jpg'),
  ('heriot', 'holo', 'cards/heriot-holo.jpg'),
  ('heriot', 'signature', 'cards/heriot-signature.jpg'),
  ('heriot', 'legendaire', 'cards/heriot-legendaire.jpg'),
  ('duplantier', 'commune', 'cards/duplantier-commune.jpg'),
  ('duplantier', 'rare', 'cards/duplantier-rare.jpg'),
  ('duplantier', 'holo', 'cards/duplantier-holo.jpg'),
  ('duplantier', 'signature', 'cards/duplantier-signature.jpg'),
  ('duplantier', 'legendaire', 'cards/duplantier-legendaire.jpg'),
  ('blink182', 'commune', 'cards/blink182-commune.jpg'),
  ('blink182', 'rare', 'cards/blink182-rare.jpg'),
  ('blink182', 'holo', 'cards/blink182-holo.jpg'),
  ('blink182', 'signature', 'cards/blink182-signature.jpg'),
  ('blink182', 'legendaire', 'cards/blink182-legendaire.jpg'),
  ('hoppus', 'commune', 'cards/hoppus-commune.jpg'),
  ('hoppus', 'rare', 'cards/hoppus-rare.jpg'),
  ('hoppus', 'holo', 'cards/hoppus-holo.jpg'),
  ('hoppus', 'signature', 'cards/hoppus-signature.jpg'),
  ('hoppus', 'legendaire', 'cards/hoppus-legendaire.jpg'),
  ('hendrix', 'commune', 'cards/hendrix-commune.jpg'),
  ('hendrix', 'rare', 'cards/hendrix-rare.jpg'),
  ('hendrix', 'holo', 'cards/hendrix-holo.jpg'),
  ('hendrix', 'signature', 'cards/hendrix-signature.jpg'),
  ('hendrix', 'legendaire', 'cards/hendrix-legendaire.jpg'),
  ('korn', 'commune', 'cards/korn-commune.jpg'),
  ('korn', 'rare', 'cards/korn-rare.jpg'),
  ('korn', 'holo', 'cards/korn-holo.jpg'),
  ('korn', 'signature', 'cards/korn-signature.jpg'),
  ('korn', 'legendaire', 'cards/korn-legendaire.jpg'),
  ('poppy', 'commune', 'cards/poppy-commune.jpg'),
  ('poppy', 'rare', 'cards/poppy-rare.jpg'),
  ('poppy', 'holo', 'cards/poppy-holo.jpg'),
  ('poppy', 'signature', 'cards/poppy-signature.jpg'),
  ('poppy', 'legendaire', 'cards/poppy-legendaire.jpg'),
  ('slash', 'commune', 'cards/slash-commune.jpg'),
  ('slash', 'rare', 'cards/slash-rare.jpg'),
  ('slash', 'holo', 'cards/slash-holo.jpg'),
  ('slash', 'signature', 'cards/slash-signature.jpg'),
  ('slash', 'legendaire', 'cards/slash-legendaire.jpg'),
  ('zack', 'commune', 'cards/zack-commune.jpg'),
  ('zack', 'rare', 'cards/zack-rare.jpg'),
  ('zack', 'holo', 'cards/zack-holo.jpg'),
  ('zack', 'signature', 'cards/zack-signature.jpg'),
  ('zack', 'legendaire', 'cards/zack-legendaire.jpg'),
  ('frusciante', 'commune', 'cards/frusciante-commune.jpg'),
  ('frusciante', 'rare', 'cards/frusciante-rare.jpg'),
  ('frusciante', 'holo', 'cards/frusciante-holo.jpg'),
  ('frusciante', 'signature', 'cards/frusciante-signature.jpg'),
  ('frusciante', 'legendaire', 'cards/frusciante-legendaire.jpg'),
  ('root', 'commune', 'cards/root-commune.jpg'),
  ('root', 'rare', 'cards/root-rare.jpg'),
  ('root', 'holo', 'cards/root-holo.jpg'),
  ('root', 'signature', 'cards/root-signature.jpg'),
  ('root', 'legendaire', 'cards/root-legendaire.jpg'),
  ('jordison', 'commune', 'cards/jordison-commune.jpg'),
  ('jordison', 'rare', 'cards/jordison-rare.jpg'),
  ('jordison', 'holo', 'cards/jordison-holo.jpg'),
  ('jordison', 'signature', 'cards/jordison-signature.jpg'),
  ('jordison', 'legendaire', 'cards/jordison-legendaire.jpg'),
  ('dickinson', 'commune', 'cards/dickinson-commune.jpg'),
  ('dickinson', 'rare', 'cards/dickinson-rare.jpg'),
  ('dickinson', 'holo', 'cards/dickinson-holo.jpg'),
  ('dickinson', 'signature', 'cards/dickinson-signature.jpg'),
  ('dickinson', 'legendaire', 'cards/dickinson-legendaire.jpg'),
  ('halford', 'commune', 'cards/halford-commune.jpg'),
  ('halford', 'rare', 'cards/halford-rare.jpg'),
  ('halford', 'holo', 'cards/halford-holo.jpg'),
  ('halford', 'signature', 'cards/halford-signature.jpg'),
  ('halford', 'legendaire', 'cards/halford-legendaire.jpg'),
  ('ozzy', 'commune', 'cards/ozzy-commune.jpg'),
  ('ozzy', 'rare', 'cards/ozzy-rare.jpg'),
  ('ozzy', 'holo', 'cards/ozzy-holo.jpg'),
  ('ozzy', 'signature', 'cards/ozzy-signature.jpg'),
  ('ozzy', 'legendaire', 'cards/ozzy-legendaire.jpg'),
  ('lemmy', 'commune', 'cards/lemmy-commune.jpg'),
  ('lemmy', 'rare', 'cards/lemmy-rare.jpg'),
  ('lemmy', 'holo', 'cards/lemmy-holo.jpg'),
  ('lemmy', 'signature', 'cards/lemmy-signature.jpg'),
  ('lemmy', 'legendaire', 'cards/lemmy-legendaire.jpg'),
  ('hetfield', 'commune', 'cards/hetfield-commune.jpg'),
  ('hetfield', 'rare', 'cards/hetfield-rare.jpg'),
  ('hetfield', 'holo', 'cards/hetfield-holo.jpg'),
  ('hetfield', 'signature', 'cards/hetfield-signature.jpg'),
  ('hetfield', 'legendaire', 'cards/hetfield-legendaire.jpg'),
  ('mustaine', 'commune', 'cards/mustaine-commune.jpg'),
  ('mustaine', 'rare', 'cards/mustaine-rare.jpg'),
  ('mustaine', 'holo', 'cards/mustaine-holo.jpg'),
  ('mustaine', 'signature', 'cards/mustaine-signature.jpg'),
  ('mustaine', 'legendaire', 'cards/mustaine-legendaire.jpg'),
  ('araya', 'commune', 'cards/araya-commune.jpg'),
  ('araya', 'rare', 'cards/araya-rare.jpg'),
  ('araya', 'holo', 'cards/araya-holo.jpg'),
  ('araya', 'signature', 'cards/araya-signature.jpg'),
  ('araya', 'legendaire', 'cards/araya-legendaire.jpg'),
  ('scott-ian', 'commune', 'cards/scott-ian-commune.jpg'),
  ('scott-ian', 'rare', 'cards/scott-ian-rare.jpg'),
  ('scott-ian', 'holo', 'cards/scott-ian-holo.jpg'),
  ('scott-ian', 'signature', 'cards/scott-ian-signature.jpg'),
  ('scott-ian', 'legendaire', 'cards/scott-ian-legendaire.jpg'),
  ('cobain', 'commune', 'cards/cobain-commune.jpg'),
  ('cobain', 'rare', 'cards/cobain-rare.jpg'),
  ('cobain', 'holo', 'cards/cobain-holo.jpg'),
  ('cobain', 'signature', 'cards/cobain-signature.jpg'),
  ('cobain', 'legendaire', 'cards/cobain-legendaire.jpg'),
  ('cornell', 'commune', 'cards/cornell-commune.jpg'),
  ('cornell', 'rare', 'cards/cornell-rare.jpg'),
  ('cornell', 'holo', 'cards/cornell-holo.jpg'),
  ('cornell', 'signature', 'cards/cornell-signature.jpg'),
  ('cornell', 'legendaire', 'cards/cornell-legendaire.jpg'),
  ('staley', 'commune', 'cards/staley-commune.jpg'),
  ('staley', 'rare', 'cards/staley-rare.jpg'),
  ('staley', 'holo', 'cards/staley-holo.jpg'),
  ('staley', 'signature', 'cards/staley-signature.jpg'),
  ('staley', 'legendaire', 'cards/staley-legendaire.jpg'),
  ('grohl', 'commune', 'cards/grohl-commune.jpg'),
  ('grohl', 'rare', 'cards/grohl-rare.jpg'),
  ('grohl', 'holo', 'cards/grohl-holo.jpg'),
  ('grohl', 'signature', 'cards/grohl-signature.jpg'),
  ('grohl', 'legendaire', 'cards/grohl-legendaire.jpg'),
  ('keenan', 'commune', 'cards/keenan-commune.jpg'),
  ('keenan', 'rare', 'cards/keenan-rare.jpg'),
  ('keenan', 'holo', 'cards/keenan-holo.jpg'),
  ('keenan', 'signature', 'cards/keenan-signature.jpg'),
  ('keenan', 'legendaire', 'cards/keenan-legendaire.jpg'),
  ('white-gluz', 'commune', 'cards/white-gluz-commune.jpg'),
  ('white-gluz', 'rare', 'cards/white-gluz-rare.jpg'),
  ('white-gluz', 'holo', 'cards/white-gluz-holo.jpg'),
  ('white-gluz', 'signature', 'cards/white-gluz-signature.jpg'),
  ('white-gluz', 'legendaire', 'cards/white-gluz-legendaire.jpg'),
  ('corpsegrinder', 'commune', 'cards/corpsegrinder-commune.jpg'),
  ('corpsegrinder', 'rare', 'cards/corpsegrinder-rare.jpg'),
  ('corpsegrinder', 'holo', 'cards/corpsegrinder-holo.jpg'),
  ('corpsegrinder', 'signature', 'cards/corpsegrinder-signature.jpg'),
  ('corpsegrinder', 'legendaire', 'cards/corpsegrinder-legendaire.jpg'),
  ('tankian', 'commune', 'cards/tankian-commune.jpg'),
  ('tankian', 'rare', 'cards/tankian-rare.jpg'),
  ('tankian', 'holo', 'cards/tankian-holo.jpg'),
  ('tankian', 'signature', 'cards/tankian-signature.jpg'),
  ('tankian', 'legendaire', 'cards/tankian-legendaire.jpg'),
  ('sykes', 'commune', 'cards/sykes-commune.jpg'),
  ('sykes', 'rare', 'cards/sykes-rare.jpg'),
  ('sykes', 'holo', 'cards/sykes-holo.jpg'),
  ('sykes', 'signature', 'cards/sykes-signature.jpg'),
  ('sykes', 'legendaire', 'cards/sykes-legendaire.jpg'),
  ('hayley', 'commune', 'cards/hayley-commune.jpg'),
  ('hayley', 'rare', 'cards/hayley-rare.jpg'),
  ('hayley', 'holo', 'cards/hayley-holo.jpg'),
  ('hayley', 'signature', 'cards/hayley-signature.jpg'),
  ('hayley', 'legendaire', 'cards/hayley-legendaire.jpg'),
  ('armstrong', 'commune', 'cards/armstrong-commune.jpg'),
  ('armstrong', 'rare', 'cards/armstrong-rare.jpg'),
  ('armstrong', 'holo', 'cards/armstrong-holo.jpg'),
  ('armstrong', 'signature', 'cards/armstrong-signature.jpg'),
  ('armstrong', 'legendaire', 'cards/armstrong-legendaire.jpg'),
  ('angus', 'commune', 'cards/angus-commune.jpg'),
  ('angus', 'rare', 'cards/angus-rare.jpg'),
  ('angus', 'holo', 'cards/angus-holo.jpg'),
  ('angus', 'signature', 'cards/angus-signature.jpg'),
  ('angus', 'legendaire', 'cards/angus-legendaire.jpg'),
  ('dio', 'commune', 'cards/dio-commune.jpg'),
  ('dio', 'rare', 'cards/dio-rare.jpg'),
  ('dio', 'holo', 'cards/dio-holo.jpg'),
  ('dio', 'signature', 'cards/dio-signature.jpg'),
  ('dio', 'legendaire', 'cards/dio-legendaire.jpg'),
  ('doro', 'commune', 'cards/doro-commune.jpg'),
  ('doro', 'rare', 'cards/doro-rare.jpg'),
  ('doro', 'holo', 'cards/doro-holo.jpg'),
  ('doro', 'signature', 'cards/doro-signature.jpg'),
  ('doro', 'legendaire', 'cards/doro-legendaire.jpg'),
  ('hammett', 'commune', 'cards/hammett-commune.jpg'),
  ('hammett', 'rare', 'cards/hammett-rare.jpg'),
  ('hammett', 'holo', 'cards/hammett-holo.jpg'),
  ('hammett', 'signature', 'cards/hammett-signature.jpg'),
  ('hammett', 'legendaire', 'cards/hammett-legendaire.jpg'),
  ('mercury', 'commune', 'cards/mercury-commune.jpg'),
  ('mercury', 'rare', 'cards/mercury-rare.jpg'),
  ('mercury', 'holo', 'cards/mercury-holo.jpg'),
  ('mercury', 'signature', 'cards/mercury-signature.jpg'),
  ('mercury', 'legendaire', 'cards/mercury-legendaire.jpg'),
  ('gerard-way', 'commune', 'cards/gerard-way-commune.jpg'),
  ('gerard-way', 'rare', 'cards/gerard-way-rare.jpg'),
  ('gerard-way', 'holo', 'cards/gerard-way-holo.jpg'),
  ('gerard-way', 'signature', 'cards/gerard-way-signature.jpg'),
  ('gerard-way', 'legendaire', 'cards/gerard-way-legendaire.jpg'),
  ('bennington', 'commune', 'cards/bennington-commune.jpg'),
  ('bennington', 'rare', 'cards/bennington-rare.jpg'),
  ('bennington', 'holo', 'cards/bennington-holo.jpg'),
  ('bennington', 'signature', 'cards/bennington-signature.jpg'),
  ('bennington', 'legendaire', 'cards/bennington-legendaire.jpg'),
  ('prince', 'commune', 'cards/prince-commune.jpg'),
  ('prince', 'rare', 'cards/prince-rare.jpg'),
  ('prince', 'holo', 'cards/prince-holo.jpg'),
  ('prince', 'signature', 'cards/prince-signature.jpg'),
  ('prince', 'legendaire', 'cards/prince-legendaire.jpg'),
  ('morello', 'commune', 'cards/morello-commune.jpg'),
  ('morello', 'rare', 'cards/morello-rare.jpg'),
  ('morello', 'holo', 'cards/morello-holo.jpg'),
  ('morello', 'signature', 'cards/morello-signature.jpg'),
  ('morello', 'legendaire', 'cards/morello-legendaire.jpg'),
  ('lars', 'commune', 'cards/lars-commune.jpg'),
  ('lars', 'rare', 'cards/lars-rare.jpg'),
  ('lars', 'holo', 'cards/lars-holo.jpg'),
  ('lars', 'signature', 'cards/lars-signature.jpg'),
  ('lars', 'legendaire', 'cards/lars-legendaire.jpg'),
  ('burton', 'commune', 'cards/burton-commune.jpg'),
  ('burton', 'rare', 'cards/burton-rare.jpg'),
  ('burton', 'holo', 'cards/burton-holo.jpg'),
  ('burton', 'signature', 'cards/burton-signature.jpg'),
  ('burton', 'legendaire', 'cards/burton-legendaire.jpg'),
  ('lombardo', 'commune', 'cards/lombardo-commune.jpg'),
  ('lombardo', 'rare', 'cards/lombardo-rare.jpg'),
  ('lombardo', 'holo', 'cards/lombardo-holo.jpg'),
  ('lombardo', 'signature', 'cards/lombardo-signature.jpg'),
  ('lombardo', 'legendaire', 'cards/lombardo-legendaire.jpg'),
  ('harris', 'commune', 'cards/harris-commune.jpg'),
  ('harris', 'rare', 'cards/harris-rare.jpg'),
  ('harris', 'holo', 'cards/harris-holo.jpg'),
  ('harris', 'signature', 'cards/harris-signature.jpg'),
  ('harris', 'legendaire', 'cards/harris-legendaire.jpg'),
  ('iommi', 'commune', 'cards/iommi-commune.jpg'),
  ('iommi', 'rare', 'cards/iommi-rare.jpg'),
  ('iommi', 'holo', 'cards/iommi-holo.jpg'),
  ('iommi', 'signature', 'cards/iommi-signature.jpg'),
  ('iommi', 'legendaire', 'cards/iommi-legendaire.jpg'),
  ('may', 'commune', 'cards/may-commune.jpg'),
  ('may', 'rare', 'cards/may-rare.jpg'),
  ('may', 'holo', 'cards/may-holo.jpg'),
  ('may', 'signature', 'cards/may-signature.jpg'),
  ('may', 'legendaire', 'cards/may-legendaire.jpg'),
  ('page', 'commune', 'cards/page-commune.jpg'),
  ('page', 'rare', 'cards/page-rare.jpg'),
  ('page', 'holo', 'cards/page-holo.jpg'),
  ('page', 'signature', 'cards/page-signature.jpg'),
  ('page', 'legendaire', 'cards/page-legendaire.jpg'),
  ('plant', 'commune', 'cards/plant-commune.jpg'),
  ('plant', 'rare', 'cards/plant-rare.jpg'),
  ('plant', 'holo', 'cards/plant-holo.jpg'),
  ('plant', 'signature', 'cards/plant-signature.jpg'),
  ('plant', 'legendaire', 'cards/plant-legendaire.jpg'),
  ('bonham', 'commune', 'cards/bonham-commune.jpg'),
  ('bonham', 'rare', 'cards/bonham-rare.jpg'),
  ('bonham', 'holo', 'cards/bonham-holo.jpg'),
  ('bonham', 'signature', 'cards/bonham-signature.jpg'),
  ('bonham', 'legendaire', 'cards/bonham-legendaire.jpg'),
  ('flea', 'commune', 'cards/flea-commune.jpg'),
  ('flea', 'rare', 'cards/flea-rare.jpg'),
  ('flea', 'holo', 'cards/flea-holo.jpg'),
  ('flea', 'signature', 'cards/flea-signature.jpg'),
  ('flea', 'legendaire', 'cards/flea-legendaire.jpg'),
  ('corey', 'commune', 'cards/corey-commune.jpg'),
  ('corey', 'rare', 'cards/corey-rare.jpg'),
  ('corey', 'holo', 'cards/corey-holo.jpg'),
  ('corey', 'signature', 'cards/corey-signature.jpg'),
  ('corey', 'legendaire', 'cards/corey-legendaire.jpg'),
  ('shinoda', 'commune', 'cards/shinoda-commune.jpg'),
  ('shinoda', 'rare', 'cards/shinoda-rare.jpg'),
  ('shinoda', 'holo', 'cards/shinoda-holo.jpg'),
  ('shinoda', 'signature', 'cards/shinoda-signature.jpg'),
  ('shinoda', 'legendaire', 'cards/shinoda-legendaire.jpg'),
  ('malakian', 'commune', 'cards/malakian-commune.jpg'),
  ('malakian', 'rare', 'cards/malakian-rare.jpg'),
  ('malakian', 'holo', 'cards/malakian-holo.jpg'),
  ('malakian', 'signature', 'cards/malakian-signature.jpg'),
  ('malakian', 'legendaire', 'cards/malakian-legendaire.jpg'),
  ('joe-duplantier', 'commune', 'cards/joe-duplantier-commune.jpg'),
  ('joe-duplantier', 'rare', 'cards/joe-duplantier-rare.jpg'),
  ('joe-duplantier', 'holo', 'cards/joe-duplantier-holo.jpg'),
  ('joe-duplantier', 'signature', 'cards/joe-duplantier-signature.jpg'),
  ('joe-duplantier', 'legendaire', 'cards/joe-duplantier-legendaire.jpg'),
  ('amy-lee', 'commune', 'cards/amy-lee-commune.jpg'),
  ('amy-lee', 'rare', 'cards/amy-lee-rare.jpg'),
  ('amy-lee', 'holo', 'cards/amy-lee-holo.jpg'),
  ('amy-lee', 'signature', 'cards/amy-lee-signature.jpg'),
  ('amy-lee', 'legendaire', 'cards/amy-lee-legendaire.jpg'),
  ('reuno', 'commune', 'cards/reuno-commune.jpg'),
  ('reuno', 'rare', 'cards/reuno-rare.jpg'),
  ('reuno', 'holo', 'cards/reuno-holo.jpg'),
  ('reuno', 'signature', 'cards/reuno-signature.jpg'),
  ('reuno', 'legendaire', 'cards/reuno-legendaire.jpg'),
  ('sam-carter', 'commune', 'cards/sam-carter-commune.jpg'),
  ('sam-carter', 'rare', 'cards/sam-carter-rare.jpg'),
  ('sam-carter', 'holo', 'cards/sam-carter-holo.jpg'),
  ('sam-carter', 'signature', 'cards/sam-carter-signature.jpg'),
  ('sam-carter', 'legendaire', 'cards/sam-carter-legendaire.jpg'),
  ('nito', 'commune', 'cards/nito-commune.jpg'),
  ('nito', 'rare', 'cards/nito-rare.jpg'),
  ('nito', 'holo', 'cards/nito-holo.jpg'),
  ('nito', 'signature', 'cards/nito-signature.jpg'),
  ('nito', 'legendaire', 'cards/nito-legendaire.jpg'),
  ('brendan-murphy', 'commune', 'cards/brendan-murphy-commune.jpg'),
  ('brendan-murphy', 'rare', 'cards/brendan-murphy-rare.jpg'),
  ('brendan-murphy', 'holo', 'cards/brendan-murphy-holo.jpg'),
  ('brendan-murphy', 'signature', 'cards/brendan-murphy-signature.jpg'),
  ('brendan-murphy', 'legendaire', 'cards/brendan-murphy-legendaire.jpg'),
  ('chino', 'commune', 'cards/chino-commune.jpg'),
  ('chino', 'rare', 'cards/chino-rare.jpg'),
  ('chino', 'holo', 'cards/chino-holo.jpg'),
  ('chino', 'signature', 'cards/chino-signature.jpg'),
  ('chino', 'legendaire', 'cards/chino-legendaire.jpg'),
  ('lzzy-hale', 'commune', 'cards/lzzy-hale-commune.jpg'),
  ('lzzy-hale', 'rare', 'cards/lzzy-hale-rare.jpg'),
  ('lzzy-hale', 'holo', 'cards/lzzy-hale-holo.jpg'),
  ('lzzy-hale', 'signature', 'cards/lzzy-hale-signature.jpg'),
  ('lzzy-hale', 'legendaire', 'cards/lzzy-hale-legendaire.jpg'),
  ('peter-hayes', 'commune', 'cards/peter-hayes-commune.jpg'),
  ('peter-hayes', 'rare', 'cards/peter-hayes-rare.jpg'),
  ('peter-hayes', 'holo', 'cards/peter-hayes-holo.jpg'),
  ('peter-hayes', 'signature', 'cards/peter-hayes-signature.jpg'),
  ('peter-hayes', 'legendaire', 'cards/peter-hayes-legendaire.jpg'),
  ('broden', 'commune', 'cards/broden-commune.jpg'),
  ('broden', 'rare', 'cards/broden-rare.jpg'),
  ('broden', 'holo', 'cards/broden-holo.jpg'),
  ('broden', 'signature', 'cards/broden-signature.jpg'),
  ('broden', 'legendaire', 'cards/broden-legendaire.jpg'),
  ('mccall', 'commune', 'cards/mccall-commune.jpg'),
  ('mccall', 'rare', 'cards/mccall-rare.jpg'),
  ('mccall', 'holo', 'cards/mccall-holo.jpg'),
  ('mccall', 'signature', 'cards/mccall-signature.jpg'),
  ('mccall', 'legendaire', 'cards/mccall-legendaire.jpg'),
  ('blythe', 'commune', 'cards/blythe-commune.jpg'),
  ('blythe', 'rare', 'cards/blythe-rare.jpg'),
  ('blythe', 'holo', 'cards/blythe-holo.jpg'),
  ('blythe', 'signature', 'cards/blythe-signature.jpg'),
  ('blythe', 'legendaire', 'cards/blythe-legendaire.jpg'),
  ('heafy', 'commune', 'cards/heafy-commune.jpg'),
  ('heafy', 'rare', 'cards/heafy-rare.jpg'),
  ('heafy', 'holo', 'cards/heafy-holo.jpg'),
  ('heafy', 'signature', 'cards/heafy-signature.jpg'),
  ('heafy', 'legendaire', 'cards/heafy-legendaire.jpg'),
  ('kowalewicz', 'commune', 'cards/kowalewicz-commune.jpg'),
  ('kowalewicz', 'rare', 'cards/kowalewicz-rare.jpg'),
  ('kowalewicz', 'holo', 'cards/kowalewicz-holo.jpg'),
  ('kowalewicz', 'signature', 'cards/kowalewicz-signature.jpg'),
  ('kowalewicz', 'legendaire', 'cards/kowalewicz-legendaire.jpg'),
  ('yates', 'commune', 'cards/yates-commune.jpg'),
  ('yates', 'rare', 'cards/yates-rare.jpg'),
  ('yates', 'holo', 'cards/yates-holo.jpg'),
  ('yates', 'signature', 'cards/yates-signature.jpg'),
  ('yates', 'legendaire', 'cards/yates-legendaire.jpg'),
  ('honeycutt', 'commune', 'cards/honeycutt-commune.jpg'),
  ('honeycutt', 'rare', 'cards/honeycutt-rare.jpg'),
  ('honeycutt', 'holo', 'cards/honeycutt-holo.jpg'),
  ('honeycutt', 'signature', 'cards/honeycutt-signature.jpg'),
  ('honeycutt', 'legendaire', 'cards/honeycutt-legendaire.jpg'),
  ('flynn', 'commune', 'cards/flynn-commune.jpg'),
  ('flynn', 'rare', 'cards/flynn-rare.jpg'),
  ('flynn', 'holo', 'cards/flynn-holo.jpg'),
  ('flynn', 'signature', 'cards/flynn-signature.jpg'),
  ('flynn', 'legendaire', 'cards/flynn-legendaire.jpg')
on conflict do nothing;

insert into public.binders (id, kind, label, sort) values
  ('all', 'collection', 'Toutes les cartes', 0),
  ('metalcore', 'style', 'Hardcore & metalcore', 1),
  ('hardcore', 'style', 'Death metal & deathcore', 2),
  ('prog', 'style', 'Metal progressif', 3),
  ('numetal', 'style', 'Nu metal', 4),
  ('alternatif', 'style', 'Metal alternatif', 5),
  ('poppunk', 'style', 'Pop punk & emo', 6),
  ('hardrock', 'style', 'Hard rock', 7),
  ('legendes', 'style', 'Légendes du rock', 8),
  ('heavy', 'style', 'Heavy metal', 9),
  ('thrash', 'style', 'Thrash', 10),
  ('grunge', 'style', 'Grunge & alternatif', 11),
  ('voix', 'instrument', 'Les voix', 12),
  ('batteurs', 'instrument', 'Les batteurs', 13),
  ('guitaristes', 'instrument', 'Les guitaristes', 14),
  ('bassistes', 'instrument', 'Les bassistes', 15),
  ('g-kl', 'band', 'Knocked Loose', 16),
  ('g-blink', 'band', 'Blink-182', 17),
  ('g-slipknot', 'band', 'Slipknot', 18),
  ('g-ratm', 'band', 'Rage Against the Machine', 19),
  ('g-metallica', 'band', 'Metallica', 20),
  ('g-slayer', 'band', 'Slayer', 21),
  ('g-maiden', 'band', 'Iron Maiden', 22),
  ('g-sabbath', 'band', 'Black Sabbath', 23),
  ('g-queen', 'band', 'Queen', 24),
  ('g-zeppelin', 'band', 'Led Zeppelin', 25),
  ('g-rhcp', 'band', 'Red Hot Chili Peppers', 26),
  ('g-lp', 'band', 'Linkin Park', 27),
  ('g-soad', 'band', 'System of a Down', 28),
  ('g-gojira', 'band', 'Gojira', 29)
on conflict (id) do update set kind = excluded.kind, label = excluded.label, sort = excluded.sort;

insert into public.binder_members (binder_id, musician_id) values
  ('all', 'knocked-loose'),
  ('all', 'isaac-hale'),
  ('all', 'jinjer'),
  ('all', 'spiritbox'),
  ('all', 'landmvrks'),
  ('all', 'ramos'),
  ('all', 'heriot'),
  ('all', 'duplantier'),
  ('all', 'blink182'),
  ('all', 'hoppus'),
  ('all', 'hendrix'),
  ('all', 'korn'),
  ('all', 'poppy'),
  ('all', 'slash'),
  ('all', 'zack'),
  ('all', 'frusciante'),
  ('all', 'root'),
  ('all', 'jordison'),
  ('all', 'dickinson'),
  ('all', 'halford'),
  ('all', 'ozzy'),
  ('all', 'lemmy'),
  ('all', 'hetfield'),
  ('all', 'mustaine'),
  ('all', 'araya'),
  ('all', 'scott-ian'),
  ('all', 'cobain'),
  ('all', 'cornell'),
  ('all', 'staley'),
  ('all', 'grohl'),
  ('all', 'keenan'),
  ('all', 'white-gluz'),
  ('all', 'corpsegrinder'),
  ('all', 'tankian'),
  ('all', 'sykes'),
  ('all', 'hayley'),
  ('all', 'armstrong'),
  ('all', 'angus'),
  ('all', 'dio'),
  ('all', 'doro'),
  ('all', 'hammett'),
  ('all', 'mercury'),
  ('all', 'gerard-way'),
  ('all', 'bennington'),
  ('all', 'prince'),
  ('all', 'morello'),
  ('all', 'lars'),
  ('all', 'burton'),
  ('all', 'lombardo'),
  ('all', 'harris'),
  ('all', 'iommi'),
  ('all', 'may'),
  ('all', 'page'),
  ('all', 'plant'),
  ('all', 'bonham'),
  ('all', 'flea'),
  ('all', 'corey'),
  ('all', 'shinoda'),
  ('all', 'malakian'),
  ('all', 'joe-duplantier'),
  ('all', 'amy-lee'),
  ('all', 'reuno'),
  ('all', 'sam-carter'),
  ('all', 'nito'),
  ('all', 'brendan-murphy'),
  ('all', 'chino'),
  ('all', 'lzzy-hale'),
  ('all', 'peter-hayes'),
  ('all', 'broden'),
  ('all', 'mccall'),
  ('all', 'blythe'),
  ('all', 'heafy'),
  ('all', 'kowalewicz'),
  ('all', 'yates'),
  ('all', 'honeycutt'),
  ('all', 'flynn'),
  ('metalcore', 'knocked-loose'),
  ('metalcore', 'isaac-hale'),
  ('metalcore', 'spiritbox'),
  ('metalcore', 'landmvrks'),
  ('metalcore', 'heriot'),
  ('metalcore', 'sykes'),
  ('metalcore', 'sam-carter'),
  ('metalcore', 'brendan-murphy'),
  ('metalcore', 'mccall'),
  ('metalcore', 'heafy'),
  ('metalcore', 'yates'),
  ('metalcore', 'honeycutt'),
  ('hardcore', 'ramos'),
  ('hardcore', 'corpsegrinder'),
  ('hardcore', 'white-gluz'),
  ('prog', 'keenan'),
  ('prog', 'duplantier'),
  ('prog', 'joe-duplantier'),
  ('prog', 'jinjer'),
  ('numetal', 'korn'),
  ('numetal', 'root'),
  ('numetal', 'jordison'),
  ('numetal', 'corey'),
  ('numetal', 'bennington'),
  ('numetal', 'shinoda'),
  ('alternatif', 'zack'),
  ('alternatif', 'morello'),
  ('alternatif', 'tankian'),
  ('alternatif', 'malakian'),
  ('alternatif', 'poppy'),
  ('alternatif', 'amy-lee'),
  ('alternatif', 'reuno'),
  ('alternatif', 'chino'),
  ('poppunk', 'blink182'),
  ('poppunk', 'hoppus'),
  ('poppunk', 'hayley'),
  ('poppunk', 'armstrong'),
  ('poppunk', 'gerard-way'),
  ('poppunk', 'kowalewicz'),
  ('hardrock', 'slash'),
  ('hardrock', 'angus'),
  ('hardrock', 'page'),
  ('hardrock', 'plant'),
  ('hardrock', 'bonham'),
  ('hardrock', 'lzzy-hale'),
  ('legendes', 'hendrix'),
  ('legendes', 'mercury'),
  ('legendes', 'prince'),
  ('legendes', 'may'),
  ('legendes', 'frusciante'),
  ('legendes', 'flea'),
  ('legendes', 'nito'),
  ('heavy', 'dickinson'),
  ('heavy', 'halford'),
  ('heavy', 'ozzy'),
  ('heavy', 'lemmy'),
  ('heavy', 'dio'),
  ('heavy', 'doro'),
  ('heavy', 'harris'),
  ('heavy', 'iommi'),
  ('heavy', 'broden'),
  ('thrash', 'hetfield'),
  ('thrash', 'mustaine'),
  ('thrash', 'araya'),
  ('thrash', 'scott-ian'),
  ('thrash', 'hammett'),
  ('thrash', 'lars'),
  ('thrash', 'burton'),
  ('thrash', 'lombardo'),
  ('thrash', 'blythe'),
  ('thrash', 'flynn'),
  ('grunge', 'cobain'),
  ('grunge', 'cornell'),
  ('grunge', 'staley'),
  ('grunge', 'grohl'),
  ('grunge', 'peter-hayes'),
  ('voix', 'knocked-loose'),
  ('voix', 'jinjer'),
  ('voix', 'spiritbox'),
  ('voix', 'landmvrks'),
  ('voix', 'ramos'),
  ('voix', 'heriot'),
  ('voix', 'hoppus'),
  ('voix', 'korn'),
  ('voix', 'poppy'),
  ('voix', 'zack'),
  ('voix', 'dickinson'),
  ('voix', 'halford'),
  ('voix', 'ozzy'),
  ('voix', 'lemmy'),
  ('voix', 'hetfield'),
  ('voix', 'mustaine'),
  ('voix', 'araya'),
  ('voix', 'cobain'),
  ('voix', 'cornell'),
  ('voix', 'staley'),
  ('voix', 'grohl'),
  ('voix', 'keenan'),
  ('voix', 'white-gluz'),
  ('voix', 'corpsegrinder'),
  ('voix', 'tankian'),
  ('voix', 'sykes'),
  ('voix', 'hayley'),
  ('voix', 'armstrong'),
  ('voix', 'dio'),
  ('voix', 'doro'),
  ('voix', 'mercury'),
  ('voix', 'gerard-way'),
  ('voix', 'bennington'),
  ('voix', 'prince'),
  ('voix', 'plant'),
  ('voix', 'corey'),
  ('voix', 'shinoda'),
  ('voix', 'malakian'),
  ('voix', 'joe-duplantier'),
  ('voix', 'amy-lee'),
  ('voix', 'reuno'),
  ('voix', 'sam-carter'),
  ('voix', 'nito'),
  ('voix', 'brendan-murphy'),
  ('voix', 'chino'),
  ('voix', 'lzzy-hale'),
  ('voix', 'peter-hayes'),
  ('voix', 'broden'),
  ('voix', 'mccall'),
  ('voix', 'blythe'),
  ('voix', 'heafy'),
  ('voix', 'kowalewicz'),
  ('voix', 'yates'),
  ('voix', 'honeycutt'),
  ('voix', 'flynn'),
  ('batteurs', 'blink182'),
  ('batteurs', 'duplantier'),
  ('batteurs', 'jordison'),
  ('batteurs', 'lars'),
  ('batteurs', 'lombardo'),
  ('batteurs', 'bonham'),
  ('guitaristes', 'isaac-hale'),
  ('guitaristes', 'hendrix'),
  ('guitaristes', 'slash'),
  ('guitaristes', 'frusciante'),
  ('guitaristes', 'root'),
  ('guitaristes', 'mustaine'),
  ('guitaristes', 'scott-ian'),
  ('guitaristes', 'angus'),
  ('guitaristes', 'hammett'),
  ('guitaristes', 'prince'),
  ('guitaristes', 'morello'),
  ('guitaristes', 'iommi'),
  ('guitaristes', 'may'),
  ('guitaristes', 'page'),
  ('guitaristes', 'malakian'),
  ('guitaristes', 'lzzy-hale'),
  ('guitaristes', 'peter-hayes'),
  ('guitaristes', 'heafy'),
  ('guitaristes', 'flynn'),
  ('bassistes', 'hoppus'),
  ('bassistes', 'lemmy'),
  ('bassistes', 'araya'),
  ('bassistes', 'burton'),
  ('bassistes', 'harris'),
  ('bassistes', 'flea'),
  ('g-kl', 'knocked-loose'),
  ('g-kl', 'isaac-hale'),
  ('g-blink', 'blink182'),
  ('g-blink', 'hoppus'),
  ('g-slipknot', 'root'),
  ('g-slipknot', 'jordison'),
  ('g-slipknot', 'corey'),
  ('g-ratm', 'zack'),
  ('g-ratm', 'morello'),
  ('g-metallica', 'hetfield'),
  ('g-metallica', 'hammett'),
  ('g-metallica', 'lars'),
  ('g-metallica', 'burton'),
  ('g-slayer', 'araya'),
  ('g-slayer', 'lombardo'),
  ('g-maiden', 'dickinson'),
  ('g-maiden', 'harris'),
  ('g-sabbath', 'ozzy'),
  ('g-sabbath', 'iommi'),
  ('g-queen', 'mercury'),
  ('g-queen', 'may'),
  ('g-zeppelin', 'page'),
  ('g-zeppelin', 'plant'),
  ('g-zeppelin', 'bonham'),
  ('g-rhcp', 'frusciante'),
  ('g-rhcp', 'flea'),
  ('g-lp', 'bennington'),
  ('g-lp', 'shinoda'),
  ('g-soad', 'tankian'),
  ('g-soad', 'malakian'),
  ('g-gojira', 'duplantier'),
  ('g-gojira', 'joe-duplantier')
on conflict do nothing;

delete from public.binder_members where (binder_id, musician_id) not in (values
  ('all', 'knocked-loose'),
  ('all', 'isaac-hale'),
  ('all', 'jinjer'),
  ('all', 'spiritbox'),
  ('all', 'landmvrks'),
  ('all', 'ramos'),
  ('all', 'heriot'),
  ('all', 'duplantier'),
  ('all', 'blink182'),
  ('all', 'hoppus'),
  ('all', 'hendrix'),
  ('all', 'korn'),
  ('all', 'poppy'),
  ('all', 'slash'),
  ('all', 'zack'),
  ('all', 'frusciante'),
  ('all', 'root'),
  ('all', 'jordison'),
  ('all', 'dickinson'),
  ('all', 'halford'),
  ('all', 'ozzy'),
  ('all', 'lemmy'),
  ('all', 'hetfield'),
  ('all', 'mustaine'),
  ('all', 'araya'),
  ('all', 'scott-ian'),
  ('all', 'cobain'),
  ('all', 'cornell'),
  ('all', 'staley'),
  ('all', 'grohl'),
  ('all', 'keenan'),
  ('all', 'white-gluz'),
  ('all', 'corpsegrinder'),
  ('all', 'tankian'),
  ('all', 'sykes'),
  ('all', 'hayley'),
  ('all', 'armstrong'),
  ('all', 'angus'),
  ('all', 'dio'),
  ('all', 'doro'),
  ('all', 'hammett'),
  ('all', 'mercury'),
  ('all', 'gerard-way'),
  ('all', 'bennington'),
  ('all', 'prince'),
  ('all', 'morello'),
  ('all', 'lars'),
  ('all', 'burton'),
  ('all', 'lombardo'),
  ('all', 'harris'),
  ('all', 'iommi'),
  ('all', 'may'),
  ('all', 'page'),
  ('all', 'plant'),
  ('all', 'bonham'),
  ('all', 'flea'),
  ('all', 'corey'),
  ('all', 'shinoda'),
  ('all', 'malakian'),
  ('all', 'joe-duplantier'),
  ('all', 'amy-lee'),
  ('all', 'reuno'),
  ('all', 'sam-carter'),
  ('all', 'nito'),
  ('all', 'brendan-murphy'),
  ('all', 'chino'),
  ('all', 'lzzy-hale'),
  ('all', 'peter-hayes'),
  ('all', 'broden'),
  ('all', 'mccall'),
  ('all', 'blythe'),
  ('all', 'heafy'),
  ('all', 'kowalewicz'),
  ('all', 'yates'),
  ('all', 'honeycutt'),
  ('all', 'flynn'),
  ('metalcore', 'knocked-loose'),
  ('metalcore', 'isaac-hale'),
  ('metalcore', 'spiritbox'),
  ('metalcore', 'landmvrks'),
  ('metalcore', 'heriot'),
  ('metalcore', 'sykes'),
  ('metalcore', 'sam-carter'),
  ('metalcore', 'brendan-murphy'),
  ('metalcore', 'mccall'),
  ('metalcore', 'heafy'),
  ('metalcore', 'yates'),
  ('metalcore', 'honeycutt'),
  ('hardcore', 'ramos'),
  ('hardcore', 'corpsegrinder'),
  ('hardcore', 'white-gluz'),
  ('prog', 'keenan'),
  ('prog', 'duplantier'),
  ('prog', 'joe-duplantier'),
  ('prog', 'jinjer'),
  ('numetal', 'korn'),
  ('numetal', 'root'),
  ('numetal', 'jordison'),
  ('numetal', 'corey'),
  ('numetal', 'bennington'),
  ('numetal', 'shinoda'),
  ('alternatif', 'zack'),
  ('alternatif', 'morello'),
  ('alternatif', 'tankian'),
  ('alternatif', 'malakian'),
  ('alternatif', 'poppy'),
  ('alternatif', 'amy-lee'),
  ('alternatif', 'reuno'),
  ('alternatif', 'chino'),
  ('poppunk', 'blink182'),
  ('poppunk', 'hoppus'),
  ('poppunk', 'hayley'),
  ('poppunk', 'armstrong'),
  ('poppunk', 'gerard-way'),
  ('poppunk', 'kowalewicz'),
  ('hardrock', 'slash'),
  ('hardrock', 'angus'),
  ('hardrock', 'page'),
  ('hardrock', 'plant'),
  ('hardrock', 'bonham'),
  ('hardrock', 'lzzy-hale'),
  ('legendes', 'hendrix'),
  ('legendes', 'mercury'),
  ('legendes', 'prince'),
  ('legendes', 'may'),
  ('legendes', 'frusciante'),
  ('legendes', 'flea'),
  ('legendes', 'nito'),
  ('heavy', 'dickinson'),
  ('heavy', 'halford'),
  ('heavy', 'ozzy'),
  ('heavy', 'lemmy'),
  ('heavy', 'dio'),
  ('heavy', 'doro'),
  ('heavy', 'harris'),
  ('heavy', 'iommi'),
  ('heavy', 'broden'),
  ('thrash', 'hetfield'),
  ('thrash', 'mustaine'),
  ('thrash', 'araya'),
  ('thrash', 'scott-ian'),
  ('thrash', 'hammett'),
  ('thrash', 'lars'),
  ('thrash', 'burton'),
  ('thrash', 'lombardo'),
  ('thrash', 'blythe'),
  ('thrash', 'flynn'),
  ('grunge', 'cobain'),
  ('grunge', 'cornell'),
  ('grunge', 'staley'),
  ('grunge', 'grohl'),
  ('grunge', 'peter-hayes'),
  ('voix', 'knocked-loose'),
  ('voix', 'jinjer'),
  ('voix', 'spiritbox'),
  ('voix', 'landmvrks'),
  ('voix', 'ramos'),
  ('voix', 'heriot'),
  ('voix', 'hoppus'),
  ('voix', 'korn'),
  ('voix', 'poppy'),
  ('voix', 'zack'),
  ('voix', 'dickinson'),
  ('voix', 'halford'),
  ('voix', 'ozzy'),
  ('voix', 'lemmy'),
  ('voix', 'hetfield'),
  ('voix', 'mustaine'),
  ('voix', 'araya'),
  ('voix', 'cobain'),
  ('voix', 'cornell'),
  ('voix', 'staley'),
  ('voix', 'grohl'),
  ('voix', 'keenan'),
  ('voix', 'white-gluz'),
  ('voix', 'corpsegrinder'),
  ('voix', 'tankian'),
  ('voix', 'sykes'),
  ('voix', 'hayley'),
  ('voix', 'armstrong'),
  ('voix', 'dio'),
  ('voix', 'doro'),
  ('voix', 'mercury'),
  ('voix', 'gerard-way'),
  ('voix', 'bennington'),
  ('voix', 'prince'),
  ('voix', 'plant'),
  ('voix', 'corey'),
  ('voix', 'shinoda'),
  ('voix', 'malakian'),
  ('voix', 'joe-duplantier'),
  ('voix', 'amy-lee'),
  ('voix', 'reuno'),
  ('voix', 'sam-carter'),
  ('voix', 'nito'),
  ('voix', 'brendan-murphy'),
  ('voix', 'chino'),
  ('voix', 'lzzy-hale'),
  ('voix', 'peter-hayes'),
  ('voix', 'broden'),
  ('voix', 'mccall'),
  ('voix', 'blythe'),
  ('voix', 'heafy'),
  ('voix', 'kowalewicz'),
  ('voix', 'yates'),
  ('voix', 'honeycutt'),
  ('voix', 'flynn'),
  ('batteurs', 'blink182'),
  ('batteurs', 'duplantier'),
  ('batteurs', 'jordison'),
  ('batteurs', 'lars'),
  ('batteurs', 'lombardo'),
  ('batteurs', 'bonham'),
  ('guitaristes', 'isaac-hale'),
  ('guitaristes', 'hendrix'),
  ('guitaristes', 'slash'),
  ('guitaristes', 'frusciante'),
  ('guitaristes', 'root'),
  ('guitaristes', 'mustaine'),
  ('guitaristes', 'scott-ian'),
  ('guitaristes', 'angus'),
  ('guitaristes', 'hammett'),
  ('guitaristes', 'prince'),
  ('guitaristes', 'morello'),
  ('guitaristes', 'iommi'),
  ('guitaristes', 'may'),
  ('guitaristes', 'page'),
  ('guitaristes', 'malakian'),
  ('guitaristes', 'lzzy-hale'),
  ('guitaristes', 'peter-hayes'),
  ('guitaristes', 'heafy'),
  ('guitaristes', 'flynn'),
  ('bassistes', 'hoppus'),
  ('bassistes', 'lemmy'),
  ('bassistes', 'araya'),
  ('bassistes', 'burton'),
  ('bassistes', 'harris'),
  ('bassistes', 'flea'),
  ('g-kl', 'knocked-loose'),
  ('g-kl', 'isaac-hale'),
  ('g-blink', 'blink182'),
  ('g-blink', 'hoppus'),
  ('g-slipknot', 'root'),
  ('g-slipknot', 'jordison'),
  ('g-slipknot', 'corey'),
  ('g-ratm', 'zack'),
  ('g-ratm', 'morello'),
  ('g-metallica', 'hetfield'),
  ('g-metallica', 'hammett'),
  ('g-metallica', 'lars'),
  ('g-metallica', 'burton'),
  ('g-slayer', 'araya'),
  ('g-slayer', 'lombardo'),
  ('g-maiden', 'dickinson'),
  ('g-maiden', 'harris'),
  ('g-sabbath', 'ozzy'),
  ('g-sabbath', 'iommi'),
  ('g-queen', 'mercury'),
  ('g-queen', 'may'),
  ('g-zeppelin', 'page'),
  ('g-zeppelin', 'plant'),
  ('g-zeppelin', 'bonham'),
  ('g-rhcp', 'frusciante'),
  ('g-rhcp', 'flea'),
  ('g-lp', 'bennington'),
  ('g-lp', 'shinoda'),
  ('g-soad', 'tankian'),
  ('g-soad', 'malakian'),
  ('g-gojira', 'duplantier'),
  ('g-gojira', 'joe-duplantier'));

insert into public.pack_types (id, label, size, binder_id) values
  ('mosh', 'Mosh Pack', 5, null),
  ('metalcore', 'Hardcore & metalcore', 5, 'metalcore'),
  ('hardcore', 'Death metal & deathcore', 5, 'hardcore'),
  ('numetal', 'Nu metal', 5, 'numetal'),
  ('poppunk', 'Pop punk & emo', 5, 'poppunk'),
  ('legendes', 'Légendes du rock', 5, 'legendes')
on conflict (id) do update set label = excluded.label, binder_id = excluded.binder_id;

insert into public.pack_odds (pack_type_id, rarity, weight) values
  ('mosh', 'commune', 60),
  ('mosh', 'rare', 25),
  ('mosh', 'holo', 10),
  ('mosh', 'signature', 4),
  ('mosh', 'legendaire', 1),
  ('metalcore', 'commune', 60),
  ('metalcore', 'rare', 25),
  ('metalcore', 'holo', 10),
  ('metalcore', 'signature', 4),
  ('metalcore', 'legendaire', 1),
  ('hardcore', 'commune', 60),
  ('hardcore', 'rare', 25),
  ('hardcore', 'holo', 10),
  ('hardcore', 'signature', 4),
  ('hardcore', 'legendaire', 1),
  ('numetal', 'commune', 60),
  ('numetal', 'rare', 25),
  ('numetal', 'holo', 10),
  ('numetal', 'signature', 4),
  ('numetal', 'legendaire', 1),
  ('poppunk', 'commune', 60),
  ('poppunk', 'rare', 25),
  ('poppunk', 'holo', 10),
  ('poppunk', 'signature', 4),
  ('poppunk', 'legendaire', 1),
  ('legendes', 'commune', 60),
  ('legendes', 'rare', 25),
  ('legendes', 'holo', 10),
  ('legendes', 'signature', 4),
  ('legendes', 'legendaire', 1)
on conflict do nothing;

insert into public.settings (key, value) values
  ('fusion_cost_commune', '3'),
  ('fusion_cost_rare', '6'),
  ('fusion_cost_holo', '12'),
  ('fusion_cost_signature', '24'),
  ('packs_per_day', '1')
on conflict (key) do nothing;

commit;
